### ISSUE TITLE
Inconsistent ystart auto-detection

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#102]
This is present in several ROMs, but the ones where I mostly consistently see it are River Raid and Demon Attack.  Open one of them and press Ctrl-r to reload them.  Eventually, you'll notice that sometimes the display starts much lower on the screen than it should, indicating a numerically lower ystart value has been computed.

For Demon Attack, normally the auto-detected ystart should be 37 with about 4-5 scanlines between the top of the window and the 'Imagic' banner.  When ystart is miscalculated, ystart is 27, and the banner is over 1 cm. below the top of the window.  This seems to be consistent, in that 27 is detected instead of 37.  There are similar issues in River Raid, but for that ROM the correct ystart is 36, and the wrong one is again 27 (note the 27, maybe there's a pattern there??).

**Comment by DirtyHairy** [comment]
Ouch. Remember when I talked about locking the detected ystart value after 30 frames (issue #43)? Well, I was very, very convinced I did, but it turns out I didn't after all. What I actually did was refactor the existing code and introduce a bug along the way that completely breaks the mechanics that are supposed to restart autodetection if ystart becomes unstable again :anguished: 

d429b79 corrects this by 1) fixing the bug and 2) introducing aforementioned logic --- the detected value is locked down after 30 stable frames. With this change, I cannot reproduce this issue anymode. However, this change has some breaking potential --- I'll try to tackle automated testing soon.

**Comment by sa666666** [comment]
This fixes the ROMs I mentioned, but here are a few more where there's still a problem:
[save-ship.zip](https://github.com/stella-emu/stella/files/819902/save-ship.zip)

Note that I know this is an auto-detection problem, since if I manually set the ystart in the properties, then the 'bouncing' of the image doesn't happen.  Now it may just be an issue with these ROMs, in which case I can just add ystart for them to the database, but it may also indicate a larger issue.

**Comment by DirtyHairy** [comment]
The problem with Save Our Ship is the ROM itself, not the algorithm: it alternates between two different scanlines in which in switches off VBLANK, and the jitter you see in the beginning is the algorithm trying to lock onto something. You can see the issue more clearly in 6502.ts which starts each frame just after ystart: there, the image keeps on jittering up and down.

Are there any other suspicious ROMs?

**Comment by sa666666** [comment]
Sorry I'm giving you examples in 'dribs and drabs' as the saying goes; the only way I find them is when manually going through the ROMs I have, and I have over 2000 of them.  For now, lets leave this open until I get through them all.

As for the Save our Ship ones, I can manually set the ystart for them.

**Comment by sa666666** [comment]
I will close this again, since all the other ROMs I found with issues were similar to 'Save our Ship', and not a problem with the algorithm itself.
