### ISSUE TITLE
Will you add support for Tournament Table?

### ISSUE THREAD

**Issue by soundsnow** [stella-emu/stella#1040]
https://github.com/mamedev/mame/blob/master/src/mame/atari/tourtabl.cpp

**Comment by ale-79** [comment]
My feeling, as a simple Stella user, is that while cool, it would be a bit outside the scope of the emulator. 

It is true that Tournament Table is heavily based on the same hardware of the VCS 2600 console, but it also has a lot of differences that would require special handling (different memory map, 6k of non bankswitched rom,  additional RIOT chip, completely different I/O mappings, etc.). Since TT is not a VCS cartridge, many of the Stella options (think e.g. "game properties") wouldn't make sense for it, and the debugger would need to be modified too (or disabled), as, again, that's not a VCS 2600 console with a cartridge and controllers attached, but a different machine. 

Just my 2c. :smiley:

**Comment by thrust26** [comment]
Thanks Alex for elaborating the differences.

For now the answer in no.
