### ISSUE TITLE
Change and/or list of Fixed Stella Debug Colors

### ISSUE THREAD

**Issue by iesposta** [stella-emu/stella#114]
I suggest the following regarding Stella Fixed Debug Colors:

1. Change missile1 to more green.
2. Change the ball to Blue.

This will make more sense since it is nearly already the spectrum colors ROYGBIV. 

3. Add the list of Debug Colors to a "Tab" like TIA, Sound... Reordered like this:

image.jpeg 
![img_1343](https://cloud.githubusercontent.com/assets/16738652/24729093/a0c682ac-1a2a-11e7-8124-8c05adf49c44.JPG)

If not #3, then just #1 & #2 changed?

**Comment by sa666666** [comment]
These aren't colours that I made up, but come from the actual NTSC/PAL palette.  So to use new ones, they have to still come from the palette.  Or put another way, I can't tweak them.  The colours are as follows:
<pre>
enum FixedColors {
  P0ColorNTSC = 0x30,
  P1ColorNTSC = 0x16,
  M0ColorNTSC = 0x38,
  M1ColorNTSC = 0x12,
  BLColorNTSC = 0x7e,
  PFColorNTSC = 0x76,
  BKColorNTSC = 0x0a,
  P0ColorPAL  = 0x62,
  P1ColorPAL  = 0x26,
  M0ColorPAL  = 0x68,
  M1ColorPAL  = 0x2e,
  BLColorPAL  = 0xde,
  PFColorPAL  = 0xd8,
  BKColorPAL  = 0x1c,
  HBLANKColor = 0x0e
};
</pre>

So you're free to inspect the rest of the palette and pick ones that are more appropriate, and I'd have no issue with changing them.  But the TIA core isn't set up to use colours other than the TIA ones, and doing so would be extremely difficult.  If you want to play with the colours, just go into the debugger and select, for example, COLUP0 and press the '+' key on the keypad.  This will cycle through all the colours, and when you find one you like, take note of the value and let me know.  Come to that, I could add a 'palette' command to the debugger prompt to show a colour swatch of all the TIA colours.

As for adding a tab to show this, that should be easy enough to do.

**Comment by thrust26** [comment]
> But the TIA core isn't set up to use colours other than the TIA ones, and doing so would be extremely difficult. 
How would an enhanced phosphor work then? Or are additional colors only possible later in the processing queue?

BTW: How about switching the palette in case of debug colors?

**Comment by sa666666** [comment]
Yes, phosphor mode is a post-processing effect that happens later in the pipeline.  The TIA outputs 128 colours, just like the real thing, and I'd like to keep it that way.  I don't want to complicate the TIA any further than it already is.  The colours are stored indexed in an array by a byte (so 256 possibilities); 128 for normal colours, and 128 for pal colour-loss (which we haven't tied into the new core yet).

As for switching the palette when using debug colours, it doesn't work that way.  When in this mode, player0, for example, always uses fixed colour $30, no matter what colour is actually written to COLUP0.  And since any colour can be written to COLUP0, all the possibilities would need to be $30.  But the same is true for the other colour registers as well.  So the whole idea breaks down.

No, the current approach is the easiest.  It's better to simply pick a more appropriate colour from the current ones to use in debug colours mode.

The following is output from a preliminary 'palette' command in the debugger prompt; it makes it easier to pick a colour you want.
![screenshot_20170406_103954](https://cloud.githubusercontent.com/assets/16061066/24755586/65514f50-1ab5-11e7-82fb-6ec13f2438b8.png)

**Comment by sa666666** [comment]
Another idiosyncrasy of this is that the fixed colours change depending on whether you're in NTSC or PAL, and also depend on which palette you use (standard, z26 or user-defined) :smile:  But I don't think it's a big deal, since the colours chosen are close enough in each palette that it should be obvious what each represents.  Also, adding a tab to display this has the nice side effect of showing colours based on the current mode and palette.  For example, if you're in NTSC mode, the colours shown in the tab will be NTSC-based.  Switch the console to PAL (with Ctrl-f), go back to the debugger, and the tab auto-magically will show the colours in PAL :)

**Comment by thrust26** [comment]
Maybe wee don't need an extra tab and just color the labels (P0, P1, M0...) in the TIA tab?

**Comment by sa666666** [comment]
I'd rather use the colour swatches than just colouring the text.  In any event, where we put it is debatable.  There's already a lot of stuff in the TIA tab, with more to come once I get to it.  Plus you mentioned putting the Audio stuff there too.  There's only so much room to work with.

**Comment by iesposta** [comment]
My update last night didn't post?

The picture and proposed Debugger Tab uses TIA colors.
My suggestion is to change BL from light purple to blue, and M1 to a different green. 
Then I changed the PAL debug colors to match the NTSC colors.

enum FixedColors {
  P0ColorNTSC = 0x30, Red
  P1ColorNTSC = 0x16, Ylo 
  M0ColorNTSC = 0x38, Ora
  •M1ColorNTSC = 0x12, = 0xC4 Grn 
  •BLColorNTSC = 0x7e, = 0x9E Blu
  PFColorNTSC = 0x76, Purple
  BKColorNTSC = 0x0a,

  P0ColorPAL  = 0x62, Red
  •P1ColorPAL  = 0x26, =0x2e Ylo
  •M0ColorPAL  = 0x68, =0x4a Ora
  •M1ColorPAL  = 0x2e, =0x34 Grn 
  •BLColorPAL  = 0xde, = 0xbc Blu 
  •PFColorPAL  = 0xd8, =0xa6 Purple
  BKColorPAL  = 0x1c,
  HBLANKColor = 0x0e

And a tab to see Debug Colors list in spectrum order: ROYGBIV
A color square, the object, the color spelled out. 
P0 and its Missile M0 are (already) Red, Orange
P1 and its Missile M1 Yellow, Green
BL Blue
PF Purple

This is easy to remember without having to look at a color chart because it starts with Red P0 and P0's missile Orange, ylo, grn, blu, purple (Ball blue, Playfield purple).

**Comment by sa666666** [comment]
If I move the TIA buttons to the left more, then it may free up enough room to put this stuff on the TIA tab.  But to be honest, I'd rather just put it in another tab, as the TIA tab is getting crowded, and having too much info there just makes things much harder to parse.  Adding a new tab isn't difficult, and is essentially 'free' (I'd say there's space for 4 more tabs, if need be).

**Comment by thrust26** [comment]
@sa666666: I'll leave that up to you. Like I said before, I tend to prefer as much information at once as possible. But many other people have different preferences.

@iesposta: BKColorPAL is very close to HBLANKColor, so we better use $0a instead.

**Comment by sa666666** [comment]
Having stuff that is immediately relevant when debugging a ROM, stepping, etc, should all be placed in the TIA tab, to see changes in real time.  I don't think that the debug colours fall under that category (for all intents and purposes, it's just a picture reminding us of the colours), so it doesn't really belong there.  Besides, I'm not finished adding relevant stuff to the TIA tab yet, so we may end up using all the current free space left.

**Comment by iesposta** [comment]
I agree BKColorPAL should match NTSC, so:

enum FixedColors {
P0ColorNTSC = 0x30, Red
P1ColorNTSC = 0x16, Ylo
M0ColorNTSC = 0x38, Ora
•M1ColorNTSC = 0x12, = 0xC4 Grn
•BLColorNTSC = 0x7e, = 0x9E Blu
PFColorNTSC = 0x76, Purple
BKColorNTSC = 0x0a,

P0ColorPAL = 0x62, Red
•P1ColorPAL = 0x26, =0x2e Ylo
•M0ColorPAL = 0x68, =0x4a Ora
•M1ColorPAL = 0x2e, =0x34 Grn
•BLColorPAL = 0xde, = 0xbc Blu
•PFColorPAL = 0xd8, =0xa6 Purple
•BKColorPAL = 0x1c, =0x0a Gray (or Grey)
HBLANKColor = 0x0e White

**Comment by sa666666** [comment]
OK, so this is decided.  I will get to it after I finish the TIA tab stuff from issue #15.

**Comment by iesposta** [comment]
I like having all info on one screen, and hate the idea of tabs since they began because we have wide displays (even in 4:3). 

Maybe just list a color square, object when viewing the TIA tab with Debug Colors?
If no space then a tab chart.

**Comment by sa666666** [comment]
**If** I can squeeze it into the TIA tab (and that's an IF), there would only be space for the colour block and the object name.

Also, I just updated the above colours, and the PF colours look nothing alike.  The PAL version ($a6) is indeed purple, but the NTSC one isn't.  I suggest to pick a different one.

**Comment by sa666666** [comment]
OK, those are the colours we'll use.  Snapshots of River Raid in NTSC and PAL as follows:
![river raid 1982 activision](https://cloud.githubusercontent.com/assets/16061066/24761013/d2070626-1ac4-11e7-825f-003cbcb43993.png)
![river raid 1982 activision pal](https://cloud.githubusercontent.com/assets/16061066/24761021/d57cb8a0-1ac4-11e7-876a-744f7a9677ba.png)

**Comment by thrust26** [comment]
Hm, the color for P0 is quite different. Why not making P0 for NTSC brighter? And maybe $2x instead of $1x.

**Comment by thrust26** [comment]
> **If** I can squeeze it into the TIA tab (and that's an IF), there would only be space for the colour block and the object name.

Just an idea:
![vdel2](https://cloud.githubusercontent.com/assets/24360774/24770010/c7cf26a4-1b08-11e7-80fb-9946dd3f854d.png)

**Comment by sa666666** [comment]
$1C for P1ColorNTSC is much closer to the PAL version (and overall is a more yellow-looking colour).  As for the background behind the labels, this is definitely doable.  But we also need to show the colours for background and hmove blanking, so it's probably better to group them all elsewhere in the widget.

**Comment by iesposta** [comment]
You're right NTSC is off yellow, but
$2x in NTSC is orange. 
(Actually $2x is an orange-brown $20 to orange $2e, and $3x is an orange red $30 to peach $3e)

A brighter yellow NTSC would be $18 or $1a
Yellow is very hard on PAL and $2e is about all you can use, darker becomes orange.  

In my first picture is appears yellow, in a the screenshot it appears more green although they are the same values.

**Comment by sa666666** [comment]
OK, I've updated the colours in https://github.com/stella-emu/stella/commit/435608422b426c9630ef9c200730243bbac2dcda.  This produces the following NTSC and PAL images.  I feel this is as close as we're going to get.
![river raid 1982 activision](https://cloud.githubusercontent.com/assets/16061066/24773097/6318c1d0-1aee-11e7-9f18-022a6a945266.png)
![river raid 1982 activision pal](https://cloud.githubusercontent.com/assets/16061066/24773105/67c87676-1aee-11e7-9f5f-1351f2949d0b.png)

**Comment by thrust26** [comment]
Fine by me.

**Comment by iesposta** [comment]
Looks good. Fine by me. 
Now do Mindmaster so we can see all the Debug colors at the bottom?
![img_0312](https://cloud.githubusercontent.com/assets/16738652/24775668/d3c11b06-1aeb-11e7-99bf-76f1caa645ae.PNG)

**Comment by sa666666** [comment]
![escape from the mindmaster 1982 arcadia](https://cloud.githubusercontent.com/assets/16061066/24775875/3579c3d6-1af9-11e7-804c-04b46ec4a243.png)
![escape from the mindmaster 1982 arcadia pal](https://cloud.githubusercontent.com/assets/16061066/24775881/3994d186-1af9-11e7-96f2-05f67780fcf4.png)

**Comment by sa666666** [comment]
Added a new debugger prompt command 'debugcolors' which shows this information, in https://github.com/stella-emu/stella/commit/7b8d579360a60d6236d0893f932e5cdb1cea7bda.  Note that I will still be adding it to the UI somewhere too.
![screenshot_20170408_001733](https://cloud.githubusercontent.com/assets/16061066/24825026/c779f51a-1bf0-11e7-8005-e003eddfaec5.png)

**Comment by ale-79** [comment]
I like the new colors and prompt commands to show the palettes.

There's one issue though (not caused by these changes): SECAM!
For fixed debug colors you need 8 separate hues plus black for VBLANK and SECAM palette only have 7 colors + black.
![debug_secam](https://cloud.githubusercontent.com/assets/24704739/24826759/89d3b7a8-1c3d-11e7-8997-a7bb355299e6.png)


I don't think it's worth wasting time and efforts to fix that, as there are only a handful of rom specifically programmed for SECAM and you can just switch to PAL palette before using the "fixed debug colors" option, but probably it should be mentioned in the debugger documentation.

**Comment by sa666666** [comment]
Yes, SECAM is the red-headed stepchild of the 2600.  I can't fix the debug colours issue with SECAM without extending the TIA to support more than 256 colours, and I'm not going to do that for reasons already stated above.  As you say, users will just have to switch to PAL in this case.  I really wonder how much SECAM is used anyway.

**Comment by ale-79** [comment]
> I really wonder how much SECAM is used anyway.
Very little, I think. Only the 4 or 5 Activision titles specifically coded for Secam consoles require to use the Secam palette. There are also few games where the colors were chosen so to look good on Pal and Secam (some Atari games from 1980-1983, and a few homebrews), but you just run those as PAL usually.
Adding a note to the documentation saying that you have to switch to PAL or NTSC palette in order to use the "fixed debug colors" would be more than enough, IMHO.

**Comment by sa666666** [comment]
The debug colours are now shown in the TIA tab too, in https://github.com/stella-emu/stella/commit/9416d5212c8c60b9ddc1e0fbec9043f49b2b7ed7.
![screenshot_20170502_185839](https://cloud.githubusercontent.com/assets/16061066/25640231/6164654e-2f69-11e7-9ac0-350b6b1a81da.png)

**Comment by thrust26** [comment]
Where are they located?

**Comment by sa666666** [comment]
Colours were changed slightly; PF and BL colours are swapped, since the layout makes more sense when placed next to the COLUxx registers.
![screenshot_20170503_200641](https://cloud.githubusercontent.com/assets/16061066/25684437/0b38fddc-303c-11e7-8547-72ddef7290e8.png)
