### ISSUE TITLE
Potential memory corruption in DPC+

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#124]
Again, I am not fully convinced whether I am looking at a bug or just missing something, so I am opening an issue instead of changing the code :smirk:

The thumbulator instance is constructed as
```
  myThumbEmulator = make_ptr<Thumbulator>
      (reinterpret_cast<uInt16*>(myProgramImage-0xC00),
       reinterpret_cast<uInt16*>(myDPCRAM),
       settings.getBool("thumb.trapfatal"),
       Thumbulator::ConfigureFor::DPCplus,
       this);
```
Now, this is fine if the image loaded is 32k, but if the image is smaller, the ROM pointer will be invalid. I guess the code will still execute fine even if ARM is called in most cases, but it might just segfault as well. @sa666666 , @SpiceWare , what do you think?

**Comment by SpiceWare** [comment]
The DPC+ cartridge class expects the ROM image to be 29K or 32K.  The 3K difference is the Harmony/Melody driver, which is at the start of the 32K ROM.  I don't recall why we supported the ROM w/out the 3K driver in place.  Custom ARM code doesn't reference the leading 3K of ROM, so it won't be accessed.  It's possible the end user could override the bank-switching of a different sized ROM to DPC+.  The cart class will expand the ROM image to 29K(+255 bytes) if that happens, that's the bit of code with minsize, though I don't know what that extra 255 is for - I suspect it's something left over from DPC.

When DPC+ was original designed we basically extended Pitfall 2's DPC, and it was likewise going to be used strictly with 6507 code.  As such we set up subroutines for random, copy memory, fill memory, etc. to be called by 6507.  About a month into the project batari had the idea to add support for custom ARM code, but we didn't fully think it through so we never set it up for the custom ARM code to call those subroutines - I ended up duplicating most of those functions in Stay Frosty 2's and Space Rocks's custom ARM code.

Since BUS and CDF were designed around ARM code we eliminated those subroutines from the driver as part of our goal to get the driver down to 2K (which frees up 1K of ROM **and** 1K of RAM as the driver's copied into RAM for performance reasons).  We did add some new subroutines that the custom ARM code can call, so the driver must be part of the ROM image.  The custom ARM code runs in Thumb mode. Those subroutines switch the ARM into 32-bit mode in order to update some registers, used for the 3-voice music and digital samples, which are not accessible in Thumb mode.  Afterward it switches back into thumb mode as it returns from the subroutine.  Thumbulator only supports thumb code, so I trap those 32-bit mode subroutine calls in order to have the cartridge class emulate them.  Search for **//BX** in Thumbulator if you wish to see how that was done.

Anyway, if you'd like to do some experiments here's 29K and 32K versions of Space Rocks: 
[spacerocks20121129_NTSC.bin.zip](https://github.com/stella-emu/stella/files/960127/spacerocks20121129_NTSC.bin.zip)
[spacerocks29K.bin.zip](https://github.com/stella-emu/stella/files/960128/spacerocks29K.bin.zip)

I stripped off the driver via the Mac's Terminal like this:
```
dd skip=3 count=29 if=spacerocks20121129_NTSC.bin of=spacerocks29K.bin bs=1024
```

That should work in Linux as well.  I don't know how to do that in Windows.

**Comment by sa666666** [comment]
The code that calls the CartDPC+ c'tor only happens when the image is either 29K or 32K, so no further checking is done here.  So when the Thumbulator object is created, the sizes work out correctly.

**Comment by DirtyHairy** [comment]
@SpiceWare : thanks alot for the detailed background on DPC+ / BUS / CDF, that'll be very handy for eventually implementing those schemes in 6502.ts. I'll also run a few test of the 29k ROM through valgrind to see if there is anything funky going on, but if the code never accesses the first 3k, there shouldn't be anyhting to find. I discarded the idea of doing this with the DPC+ demo as this doesn't run any ARM code at all :smirk:

@sa666666 I am not convinced yet. In the 32k case, `myProgramImage` is incremented by 3k on line 57, so decrementing it again by 3k when constructing the thumbulator yields a valid pointer. However, for 29k, it looks to me like the program pointer is untouched, and decrementing it by 3k should consequently point to an invalid stack location. This should be fine if the thumbulator leaves the first 3k alone, but if the ARM tries to access those, it might segfault.

**Comment by sa666666** [comment]
You're probably right.  For 29K ROMs, the first 3K was used to implement bankswitching by the Harmony cart itself, so the ROM itself should never access it (as @SpiceWare said).  But I suppose it could lead to a crash in case the ARM does something it shouldn't.  I guess the best thing to do is make the image always be 32K, and in the case of 29K ROMs, simply ignore the first 3K.  But it will still exist, so if the ARM does access it, at least it won't segfault (perhaps it could trap and enter the debugger in such a case).

**Comment by sa666666** [comment]
This is now fixed in https://github.com/stella-emu/stella/commit/ba2bed21b5e86c682f7c74cbe8a0f206a56c392d.
