### ISSUE TITLE
Odd behavior of PF Score bit

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#129]
Now, this one is quite odd and complicated to describe. 

When you enable "Drive unused TIA pins randomly on read/peed" with Warlords, you notice the playfield is flickering. This results from a typical coding error (missing #).

Now, when you then alternate between _Frame + 1_ and _Fill to Scanline_ (~line 75) options and watch the PF Score bit, you sometimes (1 out of ~5 tries) notice that the Score bit is enabled (which is result of the bug causing the playfield flickering), but the PF displayed is correct (red colors) nevertheless. And if you then change the setting of the Score bit back and forth while using _Scan + 1_ this has no effect too. The display remains correct. The Score bit seems to be completely ignored in this frame.
![scorebit](https://cloud.githubusercontent.com/assets/24360774/25779245/fd87b5ea-3313-11e7-98db-2bf00258745e.png)

Without randomizing the TIA pins, I cannot reproduce this behavior. So I suppose there is some side effect happening here.

Same in 4.73.

BTW: For debugging, it would be nice if the randomization would be deterministic. Currently, if you e.g. rewind one frame, the repeated frame generates different random bits.

**Comment by ale-79** [comment]
It happens if the Playfield Priority Bit is set too, because in that case the Score mode is always disabled, no matter the value of the Score bit. That's how it works in real hardware too.

See here:
[http://atariage.com/forums/topic/243146-stella-465-released/page-3#entry3404164](http://atariage.com/forums/topic/243146-stella-465-released/page-3#entry3404164)

**Comment by thrust26** [comment]
After almost 20 years, I still haven't gotten the TIA completely. 

You are absolutely right.  Thanks a lot!

**Comment by ale-79** [comment]
Actually, I totally forgot about that. I only remembered that I did some experiments with the score mode a while ago and went back reviewing them.

It would be nice if all the knowledge coming from the last 20 years of 2600 homebrews and emulators programming could be collected in a document instead of being scatteret in various places, but I think that would be a major undertaking!

**Comment by thrust26** [comment]
@DirtyHairy is making notes on all his finding.

Maybe it would be best to extend the Stella Programmer's Guide with all that new information.

**Comment by DirtyHairy** [comment]
> @DirtyHairy is making notes on all his finding.

Unfortunately, not really, but I'm planning on doing a writeup that describes the model of the TIA implemented in the new core to the point where it could be reimplemented from scratch. I don't know the history of the VCS homebrew community, but has there ever been a push to start a VCS wiki? Imho that would be a good place for collecting a hardware reference and putting together all the jigsaw pieces scatter over AA.

**Comment by thrust26** [comment]
I am a fan of using a Wiki. We should ask Al (AA) if he can host it.

**Comment by DirtyHairy** [comment]
That's what I'd have suggested, too :smirk: Would you do the asking (I don't know him)?

**Comment by thrust26** [comment]
Done :)

**Comment by ayarusso** [comment]
I can look into adding a Wiki to the site. It would help to know the scope you're looking for.  Just a 2600 Technical Wiki to collect and organize technical information?

**Comment by DirtyHairy** [comment]
Yes, that was what I had in mind --- a wiki for collecting technical documentation on the VCS that is currently scattered all over the forums.
