### ISSUE TITLE
Developer options

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#151]
Stella provides a lot of options which are only (or mainly) useful for developers. But those options are currently scattered in the GUI or only accessible by hotkeys. So how about adding a Developer/Development menu to the Options Menu and move those options over there?

Here is the list (may be incomplete):
- Jitter/Roll
- PAL color loss 
- Drive unused TIA pins...
- When loading a ROM, randomize...
- Random startup bank
- ALT + l (frame stats; and maybe more developer keys)
- ...? 

And maybe (not sure about those):
- Allow all 4 directions on joystick 
- Fast SC/AR BIOS (IMO fast should be default)
- ...?

Additionally these option settings should be enabled with an overall option switch (in menu and via command line), like the TV effects.

**Comment by sa666666** [comment]
This is definitely a post-5.0 thing, as I see it potentially taking a lot of time/back-and-forth discussion.  But I am not opposed to the idea.

**Comment by thrust26** [comment]
@sa666666 For sure that needs discussion! That's nothing we should hurry. IMO we should only move options which are at least 99% developer only.

**Comment by thrust26** [comment]
@sa666666 @DirtyHairy @ale-79 @SpiceWare 
So, which options should be moved (see list above) and which should be added? (also see the multiple switches in "Using the Command Line" in Stella doc.

I suggest moving from the options menu:
1. Jitter/Roll
2. PAL color loss
3. UI settings for debugger (undecided here)
4. debug colors (are they really only for developers?)

From the debugger (either move or duplicate):
1. Drive unused TIA pins... (-tiadriven)
2. When loading a ROM, randomize... (-ramrandom, -cpurandom) 

And then we can add some commandline-only options like:
1. -dis...
2. -thumb
3. -cfgdir

And a checkbox which disables/enables all developer options (e.g. randomizing RAM). With the checkbox unset, the options are set to default (for the players). If the checkbox is set, the settings chosen by the developer become active. That way you can quickly change modes, without having to change multiple options.

**Comment by ale-79** [comment]
I'd say

-dis...
-dbg...
-debug
-tiadriven
-cpurandom
-ramrandom
-thumb.trapfatal
-tia.dbgcolors (that is, the assignement of color to each object)

IMHO, The actual toggle of the debug colors should always be possible with the keyboard shotcut, even if debugger options are disabled. The same for toggling the individual objects and collisions. These all default to off when starting a game, so even if players select them by mistake they won't cause future issues.

I think PAL color loss and jitter belong to the video effects more than developer options. (In fact I'd move pal color loss from the "General" tab to the "TV Effects" one)

**Comment by ale-79** [comment]
> And a checkbox which disables/enables all developer options 

If possible, I'd like a keyboard shortcut too.

**Comment by thrust26** [comment]
Why would players care for color loss and jitter?

**Comment by ale-79** [comment]
I don't know how many players (if any!) would actually care, but I see those features as part of CRT emulation, like color bleed, scanlines and the other artifacts in the TV effects. Sure they are useful for debugging, but first of all they emulate real hardware, so I think they shouldn't be part of the developers-only options.

**Comment by thrust26** [comment]
Yea, its a matter of definition, how one categorizes. My idea are categories which make most sense for the users, e.g. to hide options from players which are not useful for them and gather them at one central point for developers. 

Following your categories, wouldn't we then have to move everything which is not emulation (e.g. all 4 directions on joystick) somewhere else?

**Comment by ale-79** [comment]
As said by @sa666666 the problem is that some option can't easily be defined as user-only rather than deveopers-only. personal preference plays a large role here. "Color loss" and "jitter" are an example of that, I think.

I believe that some users might want these two particolar options to be enabled while playing (I do), as they reflect what they see on real hardware. Games with odd scanline count, display in b/w on many PAL TVs (like the CRT TV I'm currently using) and I like to have Stella behave in the same way.
Newer CRT TVs don't show the color loss, but still have problems with such roms (The upper part of th e image shows complementary colors). Disabling "PAL color loss" allows to play roms that _are_ broken on original hardware. It's nice to have that possibility, but I prefer it not beinng the default or at least I think the option shouldn't be hidden in a developer tab.

Others options, like "tiadriven" are easier to categorize: that one exaggerates a behaviour that rarely occurs on real hardware to help find bugs in the code, so it clearly belongs to develpper options.
Moreover it breaks several original roms that play fine on the vast majority of original hardware.

Maybe "PAL color loss" and "jitter/roll" could be in both the "TV effects" and "developer options" tabs: if developer options are enabled (with the global checkbox), then use the settings the way are set in the dev tab, else use what is selected in the "TV effects".

**Comment by thrust26** [comment]
I think having them in both tabs is a good idea. And we need two sets of settings anyway.

**Comment by thrust26** [comment]
Committed the first shot for the "Developer Settings" dialog with 340c974.

As suggested, a few settings (PAL color loss and jitter) are redundant. So you can set them individually with or with developer setting mode.

**Comment by thrust26** [comment]
Done
