### ISSUE TITLE
Regression: dropped frames

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#152]
I was giving KC Munchkin Monster Maze (ROM from [here](http://atariage.com/forums/topic/234429-kc-munchkin-rom-level-design-contest/)) a try when I noticed that the screen blanks ocassionaly when the display pans. `git bisect` shows that this is a regression that crept in with 79d8ed00 . I think what happens is that the ROM only draws every odd frame during pan, and Stella only renders every even frame :smirk: Interestingly, the issue is gone when I enable phosphor.

**Comment by sa666666** [comment]
I don't see how that is possible.  Previously, the TIA code rendered into currentFrame and previousFrame, but currentFrame was always the one used to draw to the screen.  Then currentFrame and previousFrame are swapped, and the process starts over.  Now, there is only one frame (currentFrame), and the TIA renders into it and it is used to draw to the screen.  So essentially double-buffering is eliminated from the TIA class.  But each time the TIA draws to the buffer, the buffer is also drawn to the screen (they happen at the same time), so I don't see how anything was lost.

When I run that ROM in 4.7, I see the same output; every now and then the screen is essentially blanked, which is why we're getting the horrible flicker.  But to me it looks exactly the same as 5.0.

**Comment by DirtyHairy** [comment]
Hm, weird, I could swear that there is a difference between 4.7 and the current master (as is between pre - `79d8ed0` and ppost - `79d8ed0`. Bot od and new exhiibit excessive flicker and beating artifacts, but  it is only in the new builds that dislays visible blanking. However, my eyes may me foolin me :smirk:

**Comment by thrust26** [comment]
The game blanks the whole screen (I won't discuss Mr SQL's motivation here) every other frame during scrolling. 

On my LCD it looks like the screen gets completely blanked during scrolling, but that's only due to the dark playfield color ($80). If you enable the debug colors or use a bright playfield color, you can see the (flickering) movement.

**Comment by DirtyHairy** [comment]
> The game blanks the whole screen (I won't discuss Mr SQL's motivation here) every other frame during scrolling.

:) I'm pretty sure I share your point of view on that.

> Attached is a simple test program which emulates the game's flicker behavior permanently. 

Thanks alot! The test behaves the same for me on 4.7.3 as on 5.0 (*and* is suitable to inducing seizures :smirk:)

Funnily, I see extended periods (~200ms) of full blanking with the latest 5.0 during scroll even with debug colors enabled. However, when I lower the framerate (didn't think about this earlier), the effect is gone and I can see that all frames are there.

I think that what I am seeing here really is beating between my display refresh rate and the flicker. I still don't know exactly what the difference is between the old and the new builds, but I think that the changes caused a subtle timing shift that influences the beating effect. In order to test this, I changed timing from sleep to busy wait and, voila, the blanks are gone.

I agree, this is not a regression. At best, this is a reminder about the importance of beating effects. Sorry for the hassle.
