### ISSUE TITLE
High CPU usage in debugger

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#158]
The CPU load while a game is stopped in the debugger is very high. My slow Atom maxes out at 25% (draining my battery very fast). This is much higher than when playing the game.

BTW: The same problem exists in 4.7.2 too

**Comment by sa666666** [comment]
This has been reported several times, but is definitely a post-5.0 thing.  It happened when I switched from dirty updates to always updating the screen.  In emulation mode you don't notice it that much, since the screen is constantly being updated anyway.  But in UI mode it becomes noticeable, particularly when the window gets larger, as is the case with the debugger.  It's also noticeable in the ROM launcher.

I always meant to go back and fix this, since it's burning CPU time for no reason.  But there were issues that caused me to do things this way, and fixing them is non-trivial.  But I hope to finally get it fixed after the 5.0 release.

**Comment by sa666666** [comment]
I believe this is fixed with the latest dialog restructuring.
