### ISSUE TITLE
Debug colors wrong in latest

### ISSUE THREAD

**Issue by iesposta** [stella-emu/stella#162]
The Ball object is to be blue, the Playfield purple. 
In the latest pre- build those are swapped. 
red orange yellow green blue purple
P0. M0.       P1.      M1.     Ball. Playfield

**Comment by ale-79** [comment]
That was intentional, as it better fits the new layout of the TIA tab.
See [https://github.com/stella-emu/stella/issues/15#issuecomment-298948322](https://github.com/stella-emu/stella/issues/15#issuecomment-298948322) and [https://github.com/stella-emu/stella/issues/114#issuecomment-299055014](https://github.com/stella-emu/stella/issues/114#issuecomment-299055014)

**Comment by sa666666** [comment]
I suspected these changes would come back to haunt me.  We now have at least one person on AtariAge requesting the old scheme instead of the new one.

Personally, I want the debug colour swatches' relative placement in the debugger to remain the same.  They are next to their corresponding graphical registers, and also ordered left-to-right in overlapping priority.

So then we are left with the actual colours.  I don't want the change the exact colours themselves, since we've researched and made sure that the current ones match, as much as possible, in NTSC and PAL.  So the final option is which colour is used for which object.  Personally, I don't really care!  So they either roughly follow the ROYGBIV scheme, they are re-arranged to be closer to names (ie, Ball is Blue), or they are reverted to what was in Stella 4.x.

The one thing I really don't want to do, at least for the 5.0 release, is to make it user editable.  That just brings too much extra work for now, and we're very close to the 5.0 release as it, and I still don't have major feature finished.  I would be willing to add a toggle; use either the current colours or the 4.x colours.  But no editing otherwise, at least not for now.

**Comment by sa666666** [comment]
I've given this a little more thought.  I am willing after all to make it editable in the debugger, but the price we pay is a delayed 5.0 release.  I'm already behind with finishing Blargg and phosphor integration, there's still an issue with saving snapshots when phosphor is enabled, and I haven't even started on the documentation updates yet (which will be fairly huge, since so much has changed).

Since I'm behind schedule anyway, I guess it doesn't hurt to fall behind a little further.  Because at this point I'm looking at the second or third week in July for the 5.0 release, and that's assuming nothing else pops up in RL.

**Comment by DirtyHairy** [comment]
@sa666666 , it is your decision, but I would opt for adding a toggle to the debugger and pushing editable colors to beyond 5.0 (or maybe even pushing the toggle beyond 5.0). I am pretty sure that this won't be the last change request that comes up, and we're gonna have to stop the feature creep at some point :smirk:

At any rate, are there any aspects of the documentation related to the new core that you'd like me to help you with?

**Comment by TheHoboInYourRoom** [comment]
@sa666666, I would be quite fine with just a toggle. The only big problem I have with the rainbow scheme is that it breaks the pattern of objects that inherit their colors from others being colored with a lighter shade of the same hue as the "base" objects. And that's a visual mnemonic I'd like to keep using.

**Comment by sa666666** [comment]
@DirtyHairy, the major issue with documentation is looking for everything that has changed.  This includes at least the following:
- new/changed commandline options
- general descriptions of the new functionality
- mentioning specific things that need to be pointed out (in several issues/threads, we say to "make sure this is mentioned in the docs)
- updating GUI screenshots for stuff that's changed

And so on.  It's not just the work of doing this, but making sure I have all the items taken care of and haven't forgotten anything.  So even having a specific list of what needs to be done would be beneficial.

I **have** to get to the Blargg/phosphor stuff these weekend (Canada Day long weekend, but alas, it needs to be done).  And then there's the snapshot not working with the new phosphor code.  And I can't even back out the new phosphor code for a later release, since adding it has fixed some other bugs elsewhere.  I guess it was my fault for adding a major feature so late in the schedule (it was added in pre8 or so).

**Comment by DirtyHairy** [comment]
No worries, sometimes you make "only this small change", and countless hours later you stare up from a bottomless pit and wonder how that came about --- happened to me at work today, too :smirk: If removing the fallout from the phosphor changes is creating too much pressure, I do think backing out reverting it for 5.0 release is an option --- the associated bugs were minor at best (if I remember correctly), and software without bugs is an illusion anyway.

I'll try to compile a list of documentation changes this weekend.

**Comment by iesposta** [comment]
TheHoboInYourRoom: Your statement of new debug colors breaks something doesn't make sense to me. The big change is the Ball is blue. Missile1 was almost the same color as Player1, so it shifted from yellow green to clearly green. That's all. 
It never was red/pink green/light green purple/light purple. 
![img_0480](https://user-images.githubusercontent.com/16738652/27714480-29a73faa-5cff-11e7-8883-fa8aa06919f5.JPG)
![img_0481](https://user-images.githubusercontent.com/16738652/27714481-29a7ed7e-5cff-11e7-8b39-2a1cf703dd65.JPG)

**Comment by TheHoboInYourRoom** [comment]
From 4.7.3:
```
  if(myFramerate > 55.0)  // NTSC
  {
    myFixedColor[P0Color]     = 0x30;
    myFixedColor[P1Color]     = 0x16;
    myFixedColor[M0Color]     = 0x38;
    myFixedColor[M1Color]     = 0x12;
    myFixedColor[BLColor]     = 0x7e;
    myFixedColor[PFColor]     = 0x76;
    myFixedColor[BKColor]     = 0x0a;
    myFixedColor[HBLANKColor] = 0x0e;
    myColorLossEnabled = false;
    myMaximumNumberOfScanlines = 290;
  }
  else
  {
    myFixedColor[P0Color]     = 0x62;
    myFixedColor[P1Color]     = 0x26;
    myFixedColor[M0Color]     = 0x68;
    myFixedColor[M1Color]     = 0x2e;
    myFixedColor[BLColor]     = 0xde;
    myFixedColor[PFColor]     = 0xd8;
    myFixedColor[BKColor]     = 0x1c;
    myFixedColor[HBLANKColor] = 0x0e;

```
The colors for paired objects share the same top nybbles and differ only in their brightnesses. I don't know what to say other than that I've seen the Atari's palette(s) enough to intuitively know that these color pairs belong to the same chroma values. $16 and $12 in NTSC look similar in a way that $1c and $c4 don't. Likewise for the other pairs.

**Comment by thrust26** [comment]
I never cared much for the exact debug colors, but IMO he has an argument here. Giving objects which share their color the same hue and differ them only by their brightness (brighter for objects inherit their color) seems more obvious and easier to remember. 

So maybe we should keep the original colors and only slightly change them where it makes sense (compared to 4.7.3: swap NTSC P1 and M1 colors, also in PAL BkColor is very close to HmColor).

**Comment by iesposta** [comment]
Thank you for the explanation. That solves a 20+ year mystery as to the reason why the debug colors were those chosen colors. Now it makes sense looking at it from a programmers point of view!

The reasons for my proposed change were:
1. They didn't make sense, I always had to refer to chart I posted above
2. Changing Ball to blue aligned them with the easy to remember Roy G. Biv / ROYGBIV / spectrum colors

I agree it is more obvious to give the objects and those that inherit their color the same hue with different brightness to associate the Players with their Missiles and the Playfield to the Ball.

**Comment by ale-79** [comment]
I never remember the debug colors. What I do every time I use them is to disable and re-enable every object (with the combo ALT+ Z,X,C,V,B and N) to see which color correspond to each of them... :smile:

**Comment by DirtyHairy** [comment]
> I never remember the debug colors. What I do every time I use them is to disable and re-enable every object (with the combo ALT+ Z,X,C,V,B and N) to see which color correspond to each of them... :smile:

I do the same :smirk:

**Comment by thrust26** [comment]
Me too.

**Comment by sa666666** [comment]
I've added the ability to change which colours are assigned to which graphical object in https://github.com/stella-emu/stella/commit/2e776b05b8387e1e93f94ac3b34acd94ffad5c2e.  Note that you can't actually edit the colours; you have red,orange,yellow,green,blue,purple to assign to P0/M0/P1/M1/PF/BL as you see fit.  So the colours are set, but you can still re-arrange them.

For now,  and possibly for 5.0 final, this is available through a commandline option (tia.dbgcolors).  Given time, I may add a GUI for it.  I hope this will settle this issue for good.  Everyone is free to re-arrange the colours as they see fit.
