### ISSUE TITLE
Show unused RAM and ROM

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#167]
Being able to dump RAM not changed (e.g. since the last dump) and ROM never accessed would be nice.

**Comment by sa666666** [comment]
We might be able to steal a bit from the debugger codeAccessBase (basically, an 8-bit description of every byte of ROM in the system) to track this.  Otherwise, we may have to bump the access base to 16-bit (each bit tracks a different thing).  Note that this is how/where we know something is CODE vs DATA, PGFX, etc.

**Comment by thrust26** [comment]
#221 reports the required details, within the debugger this can be achieved with 
- a save state when exiting the debugger 
- not deleting previous save states when entering the debugger again
Then we can display the bytes changed between the save state and now

**Comment by thrust26** [comment]
Implemented by #221 and with cdb2e18
