### ISSUE TITLE
Center problems

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#181]
~~I have the following setup: 2 LCDs (1280x1024) and a TV (Full HD). And I can either use the 2nd LCD or the TV.~~

~~Today I tried to use Stella in fullscreen on my TV. The result was, that the fullscreen window occupied half of my 1st LCD and 2/3rd of the TV (both at full height), with large black borders left and right. I tried with different Renderers, but that made no difference. And, when switching to 4x zoom, I had the same effect.~~

~~I thought that the different resolution might be the problem, but when I reduced the resolution of my 2nd LCD, there was no problem.~~

Then I tried disabling the Center option, because it seemed that Stella may have tried to center the screen. But that had no effect. And it seems that disabling Center doesn't work at all, the window starts always at the center and even I move the window to a corner, enter the debugger and leave it again (or just change the zoom level between 2 and 3), the window is always centered again.

Am I missing something? ~~Is that a Stella problem or maybe related to my GPU (Intel) or TV (Samsung)?~~

**Comment by thrust26** [comment]
Ignore the fullscreen problems, after some fighting and experimenting with Windows setting, I managed to get a nice fullscreen on my TV:

**Comment by sa666666** [comment]
It's not surprising that there might be issues with multiple monitors.  I don't have such a setup, and have never used multiple monitors anywhere else.  I **do** have multiple monitors since I have several systems, but I've never tried hooking two (or more) up to the same system.

As for centering, it is a hint that is passed to SDL.  Per the SDL documentation, it is only a suggestion to actually do centering, which SDL is free to ignore.  Now, if it is never being ignored then perhaps it is an issue.  I will look into it.  I know for a fact that it doesn't do anything in OSX, and in fact the option is completely disabled there.

**Comment by sa666666** [comment]
After looking at the SDL documentation, this is what I can conclude:
 - Using SDL_WINDOWPOS_CENTERED_DISPLAY will center the window; this is what is used when "center" is enabled
 - Using SDL_WINDOWPOS_UNDEFINED_DISPLAY means that the user doesn't care what position the window will have; this is what is used when "center" is disabled

Now, the problem is that when the second one is used, the window is _still_ centered.  But I guess it's technically not wrong, since we told SDL we didn't care where the window was placed, and in the center is just as valid as anywhere else :imp: 

Now, I can not use the second option, and instead use the number 0.  Then the window will always open at 0,0.  I don't see this being any more valid than being centered.

I guess the best thing to do would be let the user choose the positioning, either as absolute x,y position or centering.  This has actually been requested in the past; maybe it's time to implement it.

**Comment by thrust26** [comment]
Agreed. IMO best would be to display the window where it was closed before (separately for game and debugger window?). And then the Center option would makes sense again.

But please have a look at #180 first. This is much more critical, IMO.

**Comment by sa666666** [comment]
I guess this one is now done??

**Comment by thrust26** [comment]
Depends on the answer to my question in the dev chat. :smile:

**Comment by sa666666** [comment]
What is the question again?  I think we've addressed this one, but it's up to you to keep it open or close it.

**Comment by thrust26** [comment]
> @/all I am current implementing the feature that Stella remembers the last window position and display. Do you think I should remember these separately for launcher, emulator and debugger?

**Comment by sa666666** [comment]
OK, I remember.  While I have no firm opinion (since I use centering all the time anyway), to me it makes more sense to remember them all individually.  If we're going down that path, then having it remember for one but not the others seems inconsistent.

However, like I said, I have no strong preference either way (as long as center keeps working).  Long story short; it's completely up to you.

**Comment by thrust26** [comment]
I am fine with just one setting.
