### ISSUE TITLE
Debugger command to save RAM to text file

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#202]
Self explanatory, but initially mentioned in http://atariage.com/forums/topic/267810-stella-50-released/page-4#entry3829608.

**Comment by sa666666** [comment]
Would this just save ZP RAM, or any RAM in the system (ie, from carts as well)?  The former is easy, the latter not so much (it would require infrastructure for each cart to report its RAM, and while not terribly difficult, would need to touch every bankswitching scheme).

**Comment by thrust26** [comment]
Ask Omega! 😄 

Probably both.

**Comment by ale-79** [comment]
My two cents:

You could just add the ability to ouput to file to the current "dump" command.
Moreover, instead of always dump 128 bytes, you could allow to specify start and end address and make it append text if the file already exist (also print address range, and maybe frame, scanline and CPU cycle in the output file before the dump to make it more readable. 



`dump <start address> <end address> <filename>`

e.g.
```
dump 80 ff out.txt 
dump f088 f0ff out.txt
```
This allows to dump just the part of interests, instead of the entire ram, (think about supercharger, where the entire cart space is ram, for example), and users interested in that function already know where ram is mapped anyway. Plus you can dump rom too, if you ever need that.

Maybe in the future you could even add a "dump to file" button next to RIOT RAM in the debugger and the Cartridge RAM tab, if there's one in the current scheme. but it might be overkill (I think the command line option would suffice, and it is more flexible anyway)

**Comment by Omegamatrix** [comment]
It's functionality would be to dump any type of ram.

I will give you an example of my recent usage. I was going from a menu screen to a game screen. I wanted to initialize the ram quickly to not drop the scanline count. Since I had lots of rom space the quickest way was to use tables to load the ram. It was also a superchip game.

![ram](https://user-images.githubusercontent.com/31163583/29488355-e4e128ae-84bd-11e7-9273-e7d5f3857eab.png)

Optionally in this situation being able to copy paste out of the debugger prompt would have worked as well.

**Comment by thrust26** [comment]
We already have an issue (#105) for copying and paste.

**Comment by sa666666** [comment]
I think in the long run that #105 (copy/paste) would be better here, but for now I can probably modify the 'dump' command as described by @ale-79 above.

**Comment by sa666666** [comment]
I've modified the dump command to optionally take a second argument, which indicates the end of the data range (inclusive) to dump, in https://github.com/stella-emu/stella/commit/a018dc604a5709fc5b0d06e62ef7b8dca792e6bb.

I won't be adding output to a file, since there's already a 'saveses' command that essentially does the same thing (save everything in the current debugger session to a file).  And when copy/paste is complete, that will allow yet another way to get data out of the debugger console.
