### ISSUE TITLE
CLI problems (switches and joystick)

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#209]
Strat-O-Gems Deluxe has an option, which is triggered by starting the game with joystick up or down or pressed SELECT switch.

This menu doesn't show in Stella using -holdjoy0 U or D or -holdselect. When you add -debug the corresponding checkboxes are not set in the debugger too.

[Strat-O-Gems Deluxe (2006) (John Payson).zip](https://github.com/stella-emu/stella/files/1240023/Strat-O-Gems.Deluxe.2006.John.Payson.zip)
![strat-o-gems deluxe 2006 john payson _6](https://user-images.githubusercontent.com/24360774/29536325-a4117656-86bd-11e7-8ab1-67f0e044907c.png)

This problem might exist for other games too.

**Comment by sa666666** [comment]
There are several bugs/issues here:
- There is a timer set for these options to turn off after approx. 0.5 seconds.  When starting a ROM and immediately playing, this is no problem.  When starting from the debugger, however, not enough time passes.  The reason for using the timeout is that otherwise you'd have to press Select/Reset _again_ to let the emulator know that the event is to be turned off.  I'm open to alternatives to this.
- When starting with 'debug', I think the code to process holdselect/holdreset, etc isn't even being run.
- This behaviour can also be simulated from the UI, without using the UI (right-click and select 'Power-on options'). However, the behaviour seems to be slightly different _again_.
- If you do any of the above and do a ROM reload, _then_ the menu comes up!

The last one in particular tells me that certain code sections aren't being run the first time the app starts, but after a ROM has already loaded.  This is similar in appearance (but completely different in functionality) to the recent Genesis bug.

So I have some work to do :smiley:

**Comment by sa666666** [comment]
As an aside, this is what happens to those rarely-tested parts of the code; they're likely to contain bugs.  Thanks @thrust26 and @ale-79 for reporting this.

**Comment by thrust26** [comment]
> There is a timer set for these options to turn off after approx. 0.5 seconds

The input check in Strat-O-Gems Deluxe happens after 20 frames (alternating between 20 and 297 scanlines). Not sure why this delay is coded. But I can see some scenarios where some delays might happens (e.g. controller delays, SaveKey readout)

Anyway, in this case 0.5 seconds would be sufficient, so it must be shorter currently.

**Comment by ale-79** [comment]
> When starting with 'debug', I think the code to process holdselect/holdreset, etc isn't even being run.

Actually that makes sense, as in that case you can just set the swicthes in the debugger.

**Comment by sa666666** [comment]
As mentioned above, I put a delay there to turn off the holdXXX commands.  Otherwise, using  (for example) holdselect will keep select pressed indefinitely, until you press _and release_ the Select key again.  I don't like current way it's done, and I'd rather not have a timer set like that at all.  But I couldn't think of any other way to automatically turn off these events.  Maybe I should just remove the code, and note in the documentation that you need to manually deselect them afterwards.

**Comment by sa666666** [comment]
As for 'debug' ignoring the effects of holdXXX, it may be the way the current code is, but it's not the intent.  Using one commandline argument shouldn't disable the other, unless it's specifically stated (and it isn't).  So this is a bug.

**Comment by thrust26** [comment]
Exactly.

**Comment by ale-79** [comment]
I too think it's fine keeping the input set indefinitely when using the -holdxxx commands.

I'm not sure what behaviour would be better when setting input's checkboxes in the debugger and then going back to emulation.
Should they be held or released?

And when switching to the debugger while an input is already held (either because of the -holdxxxx command or the user is actually holding the button on the controller), should the corresponding checkboxes be set or cleared? 
And what should happen in that case when you switch back to emulation?

**Comment by sa666666** [comment]
I think there is a slight misunderstanding here, so I will explain the current code:
- Stella is event-based, in that it receives input in two states; on and off (or pressed and released, if you think about keyboard keys and joystick buttons)
- the holdxxx commands set the appropriate action such that the event is 'pressed'; however, this happens without anyone actually pressing a key (it is synthetic event)
- the only way to turn off the action is for the core to receive a 'released' event (typically key up, joy button released, etc)
- however, the only way to receive such an event is to select the action _again_ (ie, you need to press _and_ release a key to get the release event).
- the other option is for a timer to go off after 500 ms to turn off all actions (ie, simulate a release event); this is what the current code does, but I'm not entirely satisfied with it, and I'd like to remove the concept of timers entirely
- there's also the option of what to do when entering the debugger wrt actions; right now, all actions are turned off before entering the debugger (all events are released), and I think the same thing happens when you exit the debugger

Anyway, all the questions need to be answered before I can fix this issue.

**Comment by thrust26** [comment]
Why are events released when entering the debugger? I cannot see a reason for that.

**Comment by sa666666** [comment]
No reason, or at least none that I can remember.

**Comment by sa666666** [comment]
Gotcha!  Or at least a start.  The problem is that the holdxxx commands set the event, but the event isn't passed to the emulation core until after one frame has been processed.  But for some ROMs (in particular the one in this thread), one frame is too late; it has missed the code that looks for Select being pressed.

I originally tested this code with Space Invaders and holdreset, and I guess it worked there because the code to process the Reset button was done _after_ the first frame.
