### ISSUE TITLE
CompuMate crashes Stella

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#229]
Selecting CompuMate as controller causes Stella to crash at (re)start.

Happens in 4.7.2 too.

**Comment by sa666666** [comment]
Bug itself is fixed in https://github.com/stella-emu/stella/commit/d99d3a16f55836e01901a2e38e9fc504d1083d71, but it leads to some further issues.  

Now that the code looks at the bankswitch scheme for CompuMate and creates the controllers accordingly, it makes no sense to manually specify 'CompuMate' as a controller type.  As such, we should probably remove all reference to that controller type, and in GameInfoDialog simply blank out the controller dropdown boxes when CM scheme is used.

In retrospect this makes sense, since the CompuMate scheme and controllers are so tightly integrated, the user should never have had the choice of changing the controllers anyway.

**Comment by sa666666** [comment]
Second issue is fixed in https://github.com/stella-emu/stella/commit/90a6c3506108367aa3660fed58f9446492ad6851.
