### ISSUE TITLE
'save' causes I/O error

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#238]
I cannot save "breaks, watches, traps to file xx" using the debugger's _save_ command. The command always return "I/O error".

I suppose this is only happening in Windows.

**Comment by ale-79** [comment]
Yup, it works here (Linux)
But I noticed something else while testing it: you can't set trap using TIA mirrors (while it seem to work for ROM and RIOT mirrors).
e.g.:
`trap 00 3f`
works fine, while
`trap 40 7f`
doesn't create any trap

**Comment by ale-79** [comment]
Nevermind, I see you already pointed out th ebug for TIA mirrors in the "conditional traps" issue.

**Comment by thrust26** [comment]
Yup, that's the potential bug I mentioned in #187. This didn't work in previous versions too, right?

**Comment by ale-79** [comment]
Currently I only have the latest stable version (5.0.2) and the up to date "master" branch. both have the issue
I'll reinstall the 4.x version to test it.

**Comment by sa666666** [comment]
I'm looking into this now.

**Comment by sa666666** [comment]
This is now fixed in https://github.com/stella-emu/stella/commit/741e148da55616b16718424a57ed83a70ceb7559.  I changed the script file extension name from '.stella' to '.script'.  Probably still have to update the documentation for this.

@thrust26. now that you can test this command, note that the current code is saving built-in functions to the script file.  Since Stella generates these automatically, they should be excluded from the output.  I leave it to you to look into this, since you'll be working on that part of the code.

**Comment by thrust26** [comment]
Will do.

**Comment by thrust26** [comment]
Done with 3fddc03
