### ISSUE TITLE
Implement E7 variations

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#260]
The known E7 bankswitching is very flexible. However I cannot find any released original ROM (only my Elite demos) where it was used that way. No clue where Kevin Horton got the original info from. Probably some of the unreleased M-Network [prototypes ](http://www.intellivisionlives.com/bluesky/games/credits/atari3.shtml#ant )use all the features of E7.

Masters of the Universe and Bump'n' Jump don't use any extra RAM and Burgertime only one single 256 bytes RAM bank (ffe8 hotspot). Like the others, Bump'n' Jump has been dumped as 16K , but only has 8K. And there also exists (at least) one prototype ROM which is similar to Burgertime, but only 8K in size too. Both use ffe4 to ffe6 as ROM hotspots. 

So these ROMs use a subset of of the known E7 bankswitching and E7 bankswitching is downward compatible. The 8K ROMs work with Stella's E7 bankswitching when they are duplicated to 16K.

Note: The ffe8 access seems superfluous, since there is only one RAM bank. Probably this was used to keep the ROM compatible with E7 hardware.  

Also: https://atariage.com/forums/topic/272581-m-network-e7-mysteries/

**Comment by thrust26** [comment]
Next finding: Burgertime is only 12K, the first 4K are duplicated.

**Comment by thrust26** [comment]
@sa666666 The code for bankswitching types like e.g. F4, F6, F8 etc. seems to be written only for one ROM size only, while others (e.g. 3F) allow multiple ROM sizes. Probably because the hotspots don't differ for the latter, but this could be addressed for the former too. 

What is the preferred solution?

Depending on the answer, the classes for E7 could be merged into one.

**Comment by sa666666** [comment]
I didn't design the original Cart class hierarchy, just used what was already there.  And the idea was to have a separate class for each logically different bankswitch type.  And for most of the classic BS types, only one size of ROM was ever really used, so that's what the code looks for.  We really need to be careful about changing any of this, since the BS autodetection heuristics depend on not only signatures in the ROM, but also file sizes themselves (in fact, file sizes are checked before the signatures are even considered).

Some other ROMs (like 3F) are defined to have several different ROM sizes, so the code tries to accommodate that too.  But they are all the same (just different size), so one class can take care of it.

As for E7, personally I would never have done any further research to find these 'sub-versions'.  Now that you have, and have created another class for it, it is fine.  But I think we could have done that within the E7 class itself.  It is definitely _cleaner_ the way you've done it, since the hotspots change, so it made sense to factor that part out.

At least I think that's what you're asking.  If you instead mean that it's possible to come up with a base class for F4, F6, F8, etc and then create subclasses with only methods for differing functionality (ie, you want to extract the commonalities into a new base class), then I am fine with doing that too.

**Comment by sa666666** [comment]
But I will add that I'd rather push any major refactoring of the Cart classes until after 5.1.

**Comment by thrust26** [comment]
Yea, after I created the stuff for E7, I found some opportunities for refactoring. But of course that will have to wait until after 5.1

But there is a general decision to be made. F4, F6, F8 etc. have all their own names in Stella (probably based on the naming in Kevtris' documents). And as far as I can tell most (except for E7, which uses padded ROMs) other old bankswitching types too. Probably a good rule would be to differ them by their hotspots. So all sizes using the same hotspot(s) will have the same name. Based on that rule, all type names can stay the same, except for the different E7 sizes. But even there, the hotspots are shared, only that the larger ROMs use more of them. So this is a corner case. 

BTW: After we discussed my findings, Kevtris is currently wondering if E7 really supported 2K of RAM. If not, then ffe7 is never used as a hotspot. And then the name E7 make no sense anymore. :smile:

**Comment by sa666666** [comment]
Sorry, not clear on what you're asking.  You say "all sizes using the same hotspot(s) will have the same name".  But then you say we already follow that rule.  So what else needs to be done?

To me, it looks like we've stated a rule and that we're already following it.  So the 'general decision' is made; we do nothing :)

**Comment by thrust26** [comment]
Yes, except for E7. That's a corner case. The hotspots are (partially) shared and the debugger widget needs  slightly different info.

**Comment by sa666666** [comment]
@thrust26, is this relevant anymore?  I know it's not done yet, but do you think we should still care about it, or leave the code as-is?

**Comment by thrust26** [comment]
Not relevant for 6.1. But for the future we should have full support.

**Comment by thrust26** [comment]
All E7 types implemented and merged with 187979a
