### ISSUE TITLE
Use file extension to detect bankswitch type

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#261]
@sa666666 Issue created following your post here:
http://atariage.com/forums/topic/249429-how-do-you-get-a-3e-rom-to-work-with-harmony-encore/#entry3447329

**Comment by sa666666** [comment]
I will get to this one personally, after the 5.1 release.  Reasons being:
- there is already code in HarmonyCart that does this
- I'm currently sharing certain autodetect code between these two projects anyway

So it makes sense to make the code fully cross-compatible, so changes in one (Stella, usually) can just be be dropped into HarmonyCart.

**Comment by thrust26** [comment]
@sa666666 Somewhat related: In the documents, there are some "future planned features" listed which have no issues yet. I wonder how many of them are still valid. Maybe you can have a look at them?

**Comment by sa666666** [comment]
Just going through the backlog of messages and noticed this one.  Where are the "future planned features" you refer to?

**Comment by thrust26** [comment]
At the end of the Features chapter in the debugger doc.

**Comment by sa666666** [comment]
Implemented in https://github.com/stella-emu/stella/commit/f0986369657f2e717b6806bdeb4fdfa845e31b24.

**Comment by thrust26** [comment]
I think we have to update the Launcher too (Filter listing...).

**Comment by sa666666** [comment]
Already in the process; note my comment in the commit: "So some functions have moved from LauncherFilterDialog to here (that class will be removed soon)."

I closed this because `LauncherFilterDialog` isn't really related to this specific issue.  But we can leave it open until I finish.

I will be removing that dialog completely, and only offering two options directing in the `LauncherDialog` context menu: 'allfiles' and 'allroms' (the naming will be different).  I'm completely removing the option to show only certain ROM filenames, as it is only adding extra complexity.

**Comment by thrust26** [comment]
Ah, sorry I missed that. I would move the option besides the already existing filter in the `LauncherDialog`. And since there are only two options, a simple checkbox (like "show all files") will do.

**Comment by sa666666** [comment]
`LauncherFilterDialog` was removed in https://github.com/stella-emu/stella/commit/65d23b4a6e81838781e0e179dd4e816b967ad4e5, so this is now complete.

**Comment by sa666666** [comment]
Oops, still have to add extension types to the docs, so re-opening.

**Comment by sa666666** [comment]
Documentation added in https://github.com/stella-emu/stella/commit/a84f76fd5f141478d49078d9308d0b50819985e6, so this is now complete.
