### ISSUE TITLE
Scan Cycle incorrect when entering debugger

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#266]
When you set a break, the Scan Cycle displayed is wrong (too low) until after you progressed e.g. by using 'Step'.

This did not happen in 4.7.2

**Comment by thrust26** [comment]
Not reproducable anymore.

**Comment by thrust26** [comment]
Ah, got it again: 

Set a trap at WSYNC. When you enter the debugger check the Scan Cycle. It is not 0 as it would be when you single step through the same instructions. Instead it seems to ignore the effect of WSYNC and display the cycle count of the previous scanline.

**Comment by DirtyHairy** [comment]
I think I know what is going on --- this is a reincarnation of #155. Trapping on WSYNC will exit `CPU::execute` before the next read cycle is executed, which implies that the CPU has not yet haltet and the TIA state has not been fast-forwarded. The reason is that I overlooked those codepaths in my previous fix for #155. I'll squish this for good this weekend.

**Comment by DirtyHairy** [comment]
Fixed with  77158fd

**Comment by thrust26** [comment]
It works, but not in all cases.

**Comment by thrust26** [comment]
Nevermind

**Comment by thrust26** [comment]
It came back! 😒 

Take any ROM and set any breakpoint. When the breakpoint is hit, the scan cycle is incorrect again. It only gets corrected with the next step. 

This is **very** irritating during kernel debugging.

**Comment by ale-79** [comment]
Seems to be fixed now with 593ec2f, I can't seem to reproduce the bug anymore.

**Comment by thrust26** [comment]
Yes, let's close it and hope it doesn't return again.
