### ISSUE TITLE
CDF crashing in debugger

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#275]
When I test Draconian or the latest version of Mappy, enter the debugger and then try to switch to the bankswitching related tabs on the right side, Stella crashes.

Maybe this only happens with my private build and/or on my 32-Bit Windows 10 convertible, so it would be nice if someone could double check.

[draconian_20171013_RC6.zip](https://github.com/stella-emu/stella/files/1584762/draconian_20171013_RC6.zip)
[mappy_20171222_beta1.zip](https://github.com/stella-emu/stella/files/1584763/mappy_20171222_beta1.zip)

**Comment by ale-79** [comment]
Confirmed (Linux 64bit).

**Comment by thrust26** [comment]
Thanks for confirming. I will take care when I am back from vacation.

**Comment by sa666666** [comment]
It's because of https://github.com/stella-emu/stella/commit/44bb4db73eadb4cd6587cd67d2ac9f65c2723440, and the removal of the call to `saveOldState(false)` in `Debugger::setStartState()`.  I don't understand the logic of why it was removed, but when I put it back, everything works fine.

I don't want to simply re-add it, though, since you made other changes, and I'm not sure of your reasoning here.

**Comment by thrust26** [comment]
That was necessary, because else change tracking did not work in case of a break. But I suppose now some initialization code is missing for CDF. It should not be very complicated to fix that.

**Comment by sa666666** [comment]
I may look into it if I find time, but maybe you're more familiar with the changes and can find it faster (when you get back).
