### ISSUE TITLE
Framebuffer left in unusable state on Raspberry Pi

### ISSUE THREAD

**Issue by mediamoshpit** [stella-emu/stella#281]
After Stella exits, it leaves the framebuffer in an unusable state, making it impossible to access command line software until the system is rebooted.

**Comment by thrust26** [comment]
Which version? Can you check with older versions (e.g. 4.x)?

**Comment by mediamoshpit** [comment]
I know the issue existed in 4.7.3. Before that, I was using 4.1.1 and the behavior wasn't present.

**Comment by sa666666** [comment]
Barring any further in-depth info on this, I cannot fix this until I get a Pi and analyze the problem.

**Comment by mediamoshpit** [comment]
Understandable. Thanks for your time.

**Comment by DirtyHairy** [comment]
@mediamoshpit, is this a standard Pi? I have access to some of those and could give it a shot when I find time.

**Comment by mediamoshpit** [comment]
I'm using a Raspberry Model 3B, but I believe it affects all models.

**Comment by sa666666** [comment]
I have ordered a Pi 3B from Amazon.  I can't say when I can get to this or if/when it can be fixed, but I will at least look into it when I have the hardware.

**Comment by mediamoshpit** [comment]
I appreciate you guys taking a look into it, no matter what the outcome.

**Comment by mediamoshpit** [comment]
SDL 2.0.6 is believed to have solved this issue. I've tested this on Raspbian Jessie and it doesn't seem to be an issue any more.

**Comment by michaelcmartin** [comment]
I can repro this issue on a Pi 3 running SDL 2.0.8 in Raspbian Stretch Lite, outside of X11 mode. The keyboard isn't being properly restored out of raw mode into normal input mode on quit. It looks like this is SDL_Quit()'s job and that wasn't being called. Adding an SDL_Quit to pair with the SDL_Init call resolved this issue for me.

I've submitted a PR to incorporate this change (referenced above) and there's also a workaround if you're in the console mode already: Alt-SysRq-r will force the console out of raw mode and restore normal operation.

**Comment by michaelcmartin** [comment]
After the work surrounding PR #389 I think I can characterize what was causing this bug. In order to trigger it Stella needed to be running on Linux _outside of X11_ and then the issue would be that the (nongraphical) console you returned to would be in the wrong mode and refuse keyboard input. It seems that fixing the keyboard state happened when calling SDL_Quit, but when running in X11 no work actually needed to be done for this (X11 is itself always in the same keyboard mode Stella is in).

This only should be an issue when running with a framebuffer driver or a console-level OpenGL or OpenGL ES system, and AIUI SDL2 doesn't actually have a framebuffer driver anymore. The Raspberry Pi doesn't support setting up OpenGL ES outside of X11 with SDL until SDL 2.0.8, and Raspbian doesn't ship with that version yet. So this isn't super-critical yet, but it will enable running with much less overhead once their repositories take those SDL2 updates.

The pending 6.0 release fixes this bug on my Pi3 system running SDL 2.0.8, and there's a specific commit that makes the issue appear or disappear depending on whether it's present. So I think this will be fixed in 6.0.

**Comment by sa666666** [comment]
This one is now fixed, and can be closed.
