### ISSUE TITLE
Collision detection error

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#289]
There seems to be a severe error in collision detection. They are (also) detected during Hblank when doing HMOVE.

The attached ROM and save state show the problem. After stepping 4x, the P0PF collision bit is set. The bug is there since 5.x.

[Thrust.zip](https://github.com/stella-emu/stella/files/1691774/Thrust.zip)

**Comment by DirtyHairy** [comment]
Collision detection currently is currently only disabled during vblank. Changing it to be disabled during hblank as well is trivial, but before making it: are we 100% sure what is the proper behavior of real hardware here?

**Comment by thrust26** [comment]
Short answer: Well, the game used to work for years. :smile:

Long answer: How can anything collide which isn't there?

**Comment by ale-79** [comment]
BTW, I had to rename the savestate file (removing ".bin") to make it work here. Are savestates named differently in Linux and Windows?

BTW 2, do collisions work during HMOVE bars? I know it's not the case here, just wondering.

**Comment by DirtyHairy** [comment]
Collisions can trigger because, even during hblank, HMOVE pulses can toggle sprites on / off and thus trigger the collision latches. Don't get me wrong, if this behavior breaks thrust, it may be wrong 😉

**Comment by DirtyHairy** [comment]
A quick and dirty way to disable this behavior is commenting out line 1210 in TIA.cxx - you can check whether this fixes any issues you encounter with Thrust.

**Comment by sa666666** [comment]
I also found I had to rename the state file (in Linux).  Since @thrust26 is using Windows, now I wonder if they do indeed generate files with different names.

I will look into this post-5.1.

**Comment by DirtyHairy** [comment]
Ah, sorry @thrust26, I see that you are talking about P0PF, this may be more subtle - the question is what defines the state of the playfield signal during HBLANK. It could be always off, retain the state of the last pixel or already be set according to the last pixel. I'll investigate once I find time.

**Comment by thrust26** [comment]
Regarding the state filenames: That's due to a mistake in my Stella.pro file, where the Thrust version's property name contains the ".bin" extension.

**Comment by DirtyHairy** [comment]
Fixed in ba549e1d. A few words on the change and on how collision detection currently works during hblank. The following seems the most natural behavior to me and is backed by my understanding of the schematics. Nevertheless, I'll open another ticket for some actual tests. In particular, I am not 100% sure about the correct behavior of the playfield signal during hblank, and my understanding of electronics is too bad to derive it from the schematics :smirk:

Collisions are tracked by latches that are set depending on the state of the sprite / playfield signals at *every* clock. During hblank, those signals do not normally change (as no pulses are sent to the sprite counters), *unless* a hmove is in progress. Hmove works by sending pulses to the sprites during hblank and may thus change the sprite signals and trigger a collision even during hblank.

The playfield is a bit special as it is not driven by a counter that is clocked during the visible part of the frame, but instead directly driven by the horizontal position counter. From my understanding, the bits in the PFx registers are shifted by the transitions of this counter and directly form the PF signal. The previous behavior of the core was to hold the last playfield pixel until the first pixel is displayed. My patch changes this to reset the playfield to pixel 0 on line wrap and start counting again at pixel 68.
