### ISSUE TITLE
Mouse sensitivity greatly varies depending on mouse grab mode

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#304]
When the mouse is not grabbed, the sensitivity is much, much higher (doubled?) than when it is grabbed. This affects paddle and trackball emulation.

The bug is there in 4.7.1 too. Since no one has mentioned it, maybe it has to do with my setup. Someone please verify.

**Comment by sa666666** [comment]
This has been true for SDL since I first started using it in Stella.  In grabbed mode, SDL must be doing something (mouse warping?) to result in such a speed reduction.

I think we should aim for the grabbed mouse mode to be the baseline, and tune everything to that.  Using paddle games without mouse grab is basically useless anyway, since the mouse moves off the end of the window but the emulation keeps running.  So this is not a use case I care about.  Let's make it work for the grabbed mode, and add instructions to that effect.

**Comment by thrust26** [comment]
OK, I will update the documentation accordingly.
