### ISSUE TITLE
RetroUSB mapping problems

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#319]
It looks like some buttons are not detected correctly.

http://atariage.com/forums/topic/279990-first-review-of-retron-77/page-4#entry4055730

**Comment by sa666666** [comment]
I actually have a SNES RetroUSB adaptor now, so I can test this again.  Personally, I'm thinking that it's because of manual mapping needed, not any problem with the device itself.  But we'll see ...

**Comment by sa666666** [comment]
SNES RetroUSB is working fine in Windows 10.  The original bug report on this was from 2014, and much has changed in Stella since then.  I haven't tested on R77; I can do that later.

I don't have an NES RetroUSB device, nor do I have an NES controller.  So I can't do any testing there.  In any event, I suspect this is strictly an issue between the OS and SDL2.  If SDL2 can't pass it to Stella correctly, then it is not really our problem.  But to know for sure, I'd need actual hardware to confirm that.

**Comment by sa666666** [comment]
SNES RetroUSB is working fine on R77 too.  I don't have any hardware to test this any further, and nobody has followed up on the bug or offered to loan/donate hardware to test this.  So that's all I can do here.
