### ISSUE TITLE
Make all settings in 'AudioDialog' immediate

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#348]
There should be no need to restart the application.

**Comment by sa666666** [comment]
Stereo/mono/byrom is now immediate, since `AudioQueue` is completely created after they have been modified.  AFAICT, all that's left are frequency and sample rate.  Those are set once, in the `SoundSDL2` c'tor, and not changed afterwards.  So I guess this needs to be factored out into a separate method.

I don't know the effect of closing and re-opening the SDL sound sub-system multiple times per app run.  It caused some problems in the past in SDL1, but they may no longer be an issue.

**Comment by sa666666** [comment]
This is now fixed, I believe.  Testing is required in Windows and OSX; I have only tested in Linux for now.  If it is acceptable, then we can remove the "(*)" text in AudioDialog, and update the docs accordingly.  Then this can be closed.

**Comment by thrust26** [comment]
I have already done the UI and doc updates.

**Comment by sa666666** [comment]
There is still the text "(*)" that needs to be removed from `AudioDialog`.  I can remove it; I just wanted you guys to test and confirm that the code is working.

**Comment by thrust26** [comment]
There is no (*) in `AudioDialog`on my computer.

**Comment by sa666666** [comment]
There is in the 6.0 release branch, which is where all work is currently being done.

**Comment by thrust26** [comment]
🤦‍♂️

**Comment by sa666666** [comment]
OK, this is now complete.
