### ISSUE TITLE
Wrong values in console info for Pick'N'Pile

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#349]
Pick'N'Pile displays ~99fps when running at 60Hz.

**Comment by DirtyHairy** [comment]
That's a consequence of two things:

1. Every second frame (as detected by the code) of P'n'P is very short terminated before the rendering starts, so that's where the 99FPS come from. I have to dig a bit deeper to see what is actually causing this; either the frames are too large, or the ROM has vsync issues.

2. The code will not clear the previous frame if a new frame is started and terminates before the visible part of the kernel starts --- that's why it doesn't flicker even though every odd frame is empty.

If frame height is the culprit, 1. might be fixed easily with adjusting the max frame height. I am not so sure about 2.; technically, it might qualify as a bug; however, it allows ROMs with pathologic frame structure like P'n'P to display correctly --- I have a tendency to leave 2. as-is for the time being.

**Comment by thrust26** [comment]
The game display is fine by me. I only wonder if we can fix the reported fps.

**Comment by ale-79** [comment]
> Every second frame (as detected by the code) of P'n'P is very short terminated before the rendering starts, so that's where the 99FPS come from. I have to dig a bit deeper to see what is actually causing this; either the frames are too large, or the ROM has vsync issues.

It's a VSYNC issue: the rom outputs 311 lines, then 3 lines of VSYNC, then 1 line, then again 3 lines of VSYNC. Stella detects 314 scanlines frames alternating with 4 scanlines ones. 

I think this should be fixed by defining a minimum scanline count per frame and by ignoring VSYNC if it happens before that count is reached, as that's how CRTs seems to behave.
So Stella shouldn't start a new frame after the short 4 scanlines one, despite the fact that the rom is generating a VSYNC pulse. The game should have a steady 318 scanlines display. 

I think this will also produce a more realistic rolling screen in case of roms outputting frames which are too large.

**Comment by thrust26** [comment]
I guess I should write a program and test with my CRT how many lines between two VSYNCs phases are ignored.

**Comment by sa666666** [comment]
For now, I've added a properties entry that forces this to PAL.  I'll leave it to you guys to decide whether we should leave this open and attempt to fix at an underlying level, or close it.

**Comment by sa666666** [comment]
Still wondering on this one.  A properties entry fixes it; do we want to fix it at a lower level?  If so, I think the issue should be renamed (or a new one created) based on the fact that it's a VSYNC issue.

**Comment by sa666666** [comment]
Also, is this related to https://github.com/stella-emu/stella/issues/316.  If so, we should close this one and point there.

**Comment by thrust26** [comment]
Good idea.

**Comment by sa666666** [comment]
Which part?  Creating a new issue, or linking it to #316?

**Comment by thrust26** [comment]
The latter. :smile:

**Comment by sa666666** [comment]
This ROM exhibits what is described in #316.  So let's move discussion there.
