### ISSUE TITLE
Exception after paste from clipboard and backspace

### ISSUE THREAD

**Issue by DirtyHairy** [stella-emu/stella#365]
Pasting text into any field (tested in the "paths" section of the settings) leaves the field seemingly filled with spaces. After that, positioning the cursor at the end of the field and hitting backspace will cause Stella to die with an exception of type `std::out_of_range` in `EditableWidget::killChar`.

It seems that the underlying string is empty after the paste.

<img width="1680" alt="bildschirmfoto 2018-08-26 um 11 31 33" src="https://user-images.githubusercontent.com/2444224/44626842-26393400-a924-11e8-8a06-f81d352e19c8.png">

**Comment by thrust26** [comment]
Copy&Paste is not supported by Stella. I wonder since when this happens.

**Comment by sa666666** [comment]
There is rudimentary copy & paste in `EditableWidget`, but it was never supposed to be used or advertised outside of Stella, since it's a WIP.  I use it for copying between fields in the GameInfoDialog, mostly.

It basically uses Ctrl-c and Ctrl-v to copy the currently selected string from one `EditableWidget` to another.  It has no interaction whatsoever with the host OS clipboard.  This is obviously something I want to do for a future release.  Perhaps we should create an issue for it (or does one already exist?).

For now, I will simply disable that functionality in `EditableWidget`.

**Comment by sa666666** [comment]
Fixed in https://github.com/stella-emu/stella/commit/409fa49aaea2c518dfc7f074956a3e27056e60d3.
