### ISSUE TITLE
Aspect ratio influences pixel width, should be height

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#368]
When switching between 50Hz and 60Hz display, the display width changes. This seems wrong.

Instead the pixel height should change, because at 50Hz, on a real CRT more scanlines are displayed within the same vertical space. Therefore the 50Hz picture should be vertically compressed instead of horizontally extended.

Also we have to clarify in the docs what an aspect ratio of 0.91 means.

**Comment by sa666666** [comment]
Hmm, we should discuss this one a little more.  It affects more than just the image; the window sizes are also affected by the ratio correction currently in effect.  So now NTSC modes don't open window the same size, and can't be made to look like they were before.

I suggest we back this out for now, and discuss for inclusion in 6.1

**Comment by thrust26** [comment]
I can make the correction based on NTSC default aspect. So that NTSC keeps its size. Would that be OK for you?

**Comment by sa666666** [comment]
I think it should wait.  Now, with NTSC < 100, nothing is happening.  I guess it should stretch vertically??

And there's also the issue that NTSC ROMs open a window of height 210, and PAL a window of height 250.  And this can be changed in the properties too.  How do we reconcile this?

It's not that I disagree with your change, just that it affects more than you might see at first glance.  And we need to think about all those side effects.

**Comment by thrust26** [comment]
Compare old and new 60Hz screens. The image is wider (unaffected by ratio) and taller (increased due to ratio) now. The overall aspect ratio is of course unchanged (same for 50Hz). 

The height should be the same for both now. 210/0.91 or 250/1.09, both resulting into ~230.

I get your point. OK for delaying.

**Comment by thrust26** [comment]
While we are at it, we should remove auto centering and discuss Y-Start and Height settings.

BTW: NTSC has a theoretical maximum of 240 display lines, PAL has 288. Of course not all are (fully) visible (only ~85%..95%). The range then would be 204 (85% NTSC) .. 274 (95% PAL).

**Comment by thrust26** [comment]
Currently the code assumes that aspect ratio always leads to a **smaller** width. However, with the corrected aspect handling, the height varies by a factor >= 1.0 (it becomes **larger**). Also the maximum zoom level does not consider the aspect ratio (theoretically it can fail already, e.g. on 4:3 monitors).

For the final solution, the **displayed** height on the monitor will stay constant between PAL and NTSC. Only the number of lines rendered will vary (less lines for NTSC, more for PAL). 

But the user can still correct the aspect ratio to match his own CRT. And this could be done either by adjusting the displayed width or the displayed height. Since we already scale the height for PAL and NTSC, I suggest that we also scale the height here.

That means, the code has to be adapted to react to varying heights correctly.

**Comment by sa666666** [comment]
Pending the arrival of hardware for R77 and Windows/macOS development, I've moved on to this issue.

I've already removed 'height' from the equation completely.  It was already removed from the UI; now it is gone from the core too.  The viewable area for the TIA will be 320x240, or multiples thereof.  Hopefully this is sufficient.  And the window sizes will stay the same all the time.  If the image needs to be moved/scaled/etc, it will be done by hardware stretch or shrink.  This part still needs to be done, since currently the window size is based on what TIA reports, when it should _always_ be the same size.  A real TV doesn't suddenly change dimensions when you play a different game, and neither should Stella.

We still need to discuss ystart.  I propose getting rid of the auto-detection completely, but perhaps keeping it there in case user adjustment is needed.  But since it's already been removed from the UI, perhaps we are killing that one too?

Anyway, my idea is to completely separate window size from TIA rendered size.  The window will always be a multiple of 320x240, or settable to a specific size (that part will come in a later discussion).  Aspect correction for NTSC vs. PAL determines how the image is rendered, but it is always inside a same-sized window.

Comments/agree/disagree??

**Comment by thrust26** [comment]
Why 320 pixel wide? Isn't that already a 2:1 stretch?

Keeping ystart and height would only make sense as another TV effect. Some CRTs zoom the image more than others, some are vertically centered a bit differently. But I don't think we should keep them.

**Comment by sa666666** [comment]
I'm _really_ confused about all this.  What I _still_ don't get, after all these years, is what is the actual resolution of a TV?  I mean, it doesn't have to be 320, it just made sense that it would be.  Whatever it is though, I want to make a decision on it and stick with it.  More to the point, I want it to be a `constexpr`, not a variable.  I want to make _some_ assumptions about window sizes and stick to it.

As for `ystart` and `height`.  The latter is already gone, and if we do our jobs correctly, the former can disappear too.  I'm all for getting rid of as much of this as possible, since it only complicates the rest of the code.  These are artifacts of software rendering modes, which I don't care to go back to.

As for 240 not being enough, I'm going by your calculation above where you say ~230 is sufficient.  I figured bump it to 240, since 320x240 is a standard resolution, and also an even multiple of 1280x720 (vertically at least).

**Comment by DirtyHairy** [comment]
Here's a slightly simpler way to think about it (imho). The PAL image is 160x250 pixels. This is scaled to fit in the maximal 4:3 sized subsection on the screen. For 720p, this is 960x720, So that's what we scale the original 160x250 sized TIA image to.

If I am not mistaken, that's all that is to it: identify the largest 4:3 sized area on the target screen, scale the TIA image accordingly and then center it.

**Comment by thrust26** [comment]
The actual TV resolution is (~):
- NTSC: 720 x 525 (486 visible, ~92%)
- PAL:  720 x 625 (576 visible, ~92%) 

But the TIA doesn't cover it completely, there are fixed borders left and right and developer defined border top and bottom. I am not 100% sure, but horizontally that might be 640 pixel.

**Comment by thrust26** [comment]
@DirtyHairy The TIA image is not 100% filling the TV screen. And when scaling we have to consider the different pixel aspect ratio of NTSC and PAL. But besides that you are right.

**Comment by sa666666** [comment]
@thrust26, let's move our discussion back to gitter, since we're splitting it now 😈

**Comment by sa666666** [comment]
Current code always opens a 640x480 (or multiple of 320x240) window, so it gets 4:3 by default.  The aspect settings in the UI are not used anymore in the code.  So we need to decide if we want to keep them, and if so, what purpose they now serve.

**Comment by thrust26** [comment]
I can see two purposes:
- as an TV effect, a circle is not always a circle on some TVs
- as a developer option which allows non-fractional pixel sizes

The former only needs one value (because the calibration should be the same, independently from TV format). For the latter we would only need a checkbox.

**Comment by sa666666** [comment]
I assume for the former, you mean stretching/shrinking the vertical dimension?  So the output window stays the same size, but the actual image inside it is stretched/shrunk?  If so, I guess we need to define what 100% means, and what less than/greater than mean too.  Or maybe use a different scale?  And finally, are these to be saved as ROM properties, or just one system-wide setting??

Not sure what you mean by the latter.

**Comment by thrust26** [comment]
For the former: Yes. IMO a zero based percentage scale should do.
For the latter: Each pixel should have the same width and height. E.g. 3x2 screen pixel, not 2.9x2.1.

Both are only icing on the cake, IMO.

**Comment by sa666666** [comment]
OK, I've been looking over this for a while, and I'm utterly confused.  So let's go with a ROM that we are very sure about: Acid Drop by @thrust26.  It helps to have the author of the ROM in this discussion :smiling_imp: 

How _should_ this ROM be detected?  Right now it's NTSC, and the bottom is cut off.  If I force it to NTSC50, then it seems to display fine.

So, first question is, which is correct?  Second question is, what should `TIAConstants::viewableHeight` be set to?  Currently it's 240, but I guess we could go to 250.

Overall, I'm _still_ confused about NTSC vs. PAL.  I can't believe that after 15+ years looking at this stuff that I __still__ can't wrap my brain around it.  Am I burnt out, or just extremely dense??

Anyway, the way the current code works is to map the TIA texture into a 320x240 'TV' screen (or 320x250 if we change it).  I'm trying to reconcile the fact that a real TV has a set width and height, and if you run a PAL ROM on such a TV, the image will be squished vertically.  Is this right?  Is it that a PAL 'scanline' is narrower than an NTSC one?  Arrgh, help me :pray: 

[acid_drop.zip](https://github.com/stella-emu/stella/files/3512630/acid_drop.zip)

**Comment by sa666666** [comment]
Just to clarify, before I give up and go to bed:
- A real TV has a physical size that doesn't change.  I want to emulate that by having a pre-defined window size that doesn't change (ignore scaling of the window, as that's an after-effect).  So say our window/TV is 320x250.  I will call this our VTV (virtual TV).  I'm assuming TV's in PAL-land are also 4:3, and aren't some different shape??
- I want the image, whether it's from NTSC _or_ PAL, to be scaled into the VTV.  This means that a PAL image will be squished from it's actual number of scanlines to whatever will fit into the VTV.  First of all, is this correct?  It seems correct to me, but as I've never seen a PAL TV before, I don't know for sure.
- Once the NTSC/PAL image are scaled to the VTV, should the images should look roughly the same?  Or should one have vertical black bars??

This is really kicking my ass.  And not being able to see a real PAL TV makes it __really__ hard to visualize.  And I'm also confused between analog and digital.  I'm thinking of digital and a set number of scanlines, but the 2600 is obviously analog, with no real concept of a pixel at all.

**Comment by snes2600** [comment]
I think there's a total of 262 NTSC-60 scanlines, which includes blanking and syncing. And 312 on PAL-50. But a CRT can be a "dumb" device and we can extend the drawing period but dip below the nominal fps.

This seems to confirm that 2600 can go past the normal overscan limits.
http://www.ataricompendium.com/faq/vcs_scanlines.html


For a real TV, the Pixel Aspect Ratio (par) I think is generally always going to be the same per scanline. Basically the width of each analog pixel. Although I guess this can vary also, but we have a theoretical way to math it.

The vertical scanline part I always find confusing. But if we draw the entire TV image, we normally always have those black lines. Because 240p only draws to the same half of the lines, NTSC or PAL. If we adjust the Pot settings on the TV, then I think it normally just brings the lines closer to each other. When it hits a critical point and there's no more black bars left to trim down, then it will start squishing them together.

I currently thought (from snes experience) that PAL is just fatter width pixels than NTSC but same generic "height" or "look" otherwise. Just PAL-50 has lots more black bars to deal with in an uncropped image.


I've never grown up with a CRT so I could easily be misunderstanding this.

**Comment by thrust26** [comment]
Some confusion on this. :smile:

First Acid Drop is maybe not the best example. The original game is not done by me. It is PAL-50 and uses a lot of scanlines. The ROM @sa666666 posted is my NTSC-60 conversion. Here is the original one:
[Acid Drop (1992) (Salu, Dennis M. Kiss) (460758) (PAL) ~.zip](https://github.com/stella-emu/stella/files/3512723/Acid.Drop.1992.Salu.Dennis.M.Kiss.460758.PAL.zip)

If I understand the code correctly, the `viewableHeight` defines the buffer for which we generate the TIA output. And then we scale that output, so that it matches the correct aspect ratio. Is that correct?

Acid Drop is the known ROM which seems to utilize most vertical lines (342 max). Out of these, 249 are used for display (start and end of black boxes). So we would have to generate at least these 249 lines.

And for running a PAL ROM on a real TV: No, the **image** will not be squished, but the lines are, because it has more of them. My TV switches between NTSC and PAL mode at a certain point (284 lines, IIRC). Below and above the point, the scanlines have a different, but then **fixed** height. I assume the factor between NTSC-50 and PAL-50 lines is ~312/262. So NTSC-50 lines are ~19% taller than PAL-50 lines. Does that help your 🙏 ?

**Comment by thrust26** [comment]
> * A real TV has a physical size that doesn't change. 

Correct.

> I want to emulate that by having a pre-defined window size that doesn't change (ignore scaling of the window, as that's an after-effect). So say our window/TV is 320x250.

This size should be only related to the emulation, not the TV. Because for the latter, the sizes are different.

> I'm assuming TV's in PAL-land are also 4:3, and aren't some different shape??

Correct.

> * I want the image, whether it's from NTSC _or_ PAL, to be scaled into the VTV.  This means that a PAL image will be squished from it's actual number of scanlines to whatever will fit into the VTV.  First of all, is this correct?  It seems correct to me, but as I've never seen a PAL TV before, I don't know for sure.

No, I want to generate output for the VTV, which is then scaled to fit into the TV output. This is true for both, NTSC and PAL. Their different aspect ratio defines if the lines are more or less scaled vertically. Do not base your thoughts on NTSC, base it on the fixed size of the TV.

> * Once the NTSC/PAL image are scaled to the VTV, should the images should look roughly the same?  Or should one have vertical black bars??

Based on what? If it is the same (NTSC) image, then PAL TVs would switch to NTSC mode. :smile: If  one image is NTSC and one is PAL, then there size of vertical bars should be identical.

> This is really kicking my ass. And not being able to see a real PAL TV makes it **really** hard to visualize. And I'm also confused between analog and digital. I'm thinking of digital and a set number of scanlines, but the 2600 is obviously analog, with no real concept of a pixel at all.

PAL TVs look exactly like NTSC TVs. And a NTSC ROM on a PAL TV is displayed at 60Hz, so it looks(except for the colors), exactly like on a NTSC TV. Now, if this ROM is converted to PAL by only increasing the vblank and overscan times, then you get larger vertical bars. If the conversion is done by also increasing the vertical size of the display kernel, then the vertical bars on TV are identical.

Bad conversion: River Raid
[River Raid - Jagdflieger (1982) (Activision, Carol Shaw - Ariola) (EAX-020, EAX-020-04B, EAX-020-04I - 711 020-720) (PAL).zip](https://github.com/stella-emu/stella/files/3512741/River.Raid.-.Jagdflieger.1982.Activision.Carol.Shaw.-.Ariola.EAX-020.EAX-020-04B.EAX-020-04I.-.711.020-720.PAL.zip)

Good Conversion: Demons To Diamonds
[Demons to Diamonds (Hot Rox) (Paddle) (1982) (Atari, Alan J. Murphy, Nick 'Sandy Maiwald' Turner) (CX2615) (PAL).zip](https://github.com/stella-emu/stella/files/3512745/Demons.to.Diamonds.Hot.Rox.Paddle.1982.Atari.Alan.J.Murphy.Nick.Sandy.Maiwald.Turner.CX2615.PAL.zip)

**Comment by thrust26** [comment]
> For a real TV, the Pixel Aspect Ratio (par) I think is generally always going to be the same per scanline. Basically the width of each analog pixel. Although I guess this can vary also, but we have a theoretical way to math it.

The pixel aspect ratio varies a lot between 50 and 60Hz displays. And slightly between the individual TVs. It may even slightly change when a TV warms up. 

> Because 240p only draws to the same half of the lines, NTSC or PAL. If we adjust the Pot settings on the TV, then I think it normally just brings the lines closer to each other. When it hits a critical point and there's no more black bars left to trim down, then it will start squishing them together.

Nope, the black and the enable lines are treated the same. So if you adjust the pot, both become taller or less tall.

**Comment by sa666666** [comment]
It's obvious that we need to collaborate on this one.  I understand the current code, but what it does, not why it's doing it.  And you understand the 'why'.

Overall, still a little confused ...

**Comment by snes2600** [comment]
The **image** is a **fixed** size dimension.
- My 16" LCD is m x n inches
- Desktop resolution is set at 1920x1080.

No more resizing.


We now draw **x scanlines** into this image. But each scanline has a **varying** thickness or tallness.

ex.
240 = 1.00 thick
239 = 1.01 thick
238 = 1.02 thick
237 = 1.03 thick
236 = 1.04 thick
..


240 = 1.00 thick
241 = 0.99 thick
242 = 0.98 thick
243 = 0.97 thick
244 = 0.96 thick
..

Where thickness depends on output scaling size.

And PAL, NTSC affect the colors. Or whether we want to add more blank scanlines into the picture.

I think this is right?

**Comment by thrust26** [comment]
Initially I thought the same, but at least on my TV (and one more I know about), there are only two line thicknesses, one for NTSC and one for PAL. So the scanline frequency seems to have only two value, not variable ones. 

A 262 scanline ROM ends at line Y on the display, each extra scanline extends the image down. Until the threshold for PAL is reached. Then the bottom of the displayed image jumps up, because the scanlines become less thick.

**Comment by DirtyHairy** [comment]
That's how I'd look at it: a TV set displays a fixed amount of scanlines with a fixed aspect ratio of 4:3. The number of scanlines depends on PAL or NTSC, but for each of those two, it is fixed. I a ROM draws less scanlines, the remaining scanlines are blank. If a ROM draws more scanlines, some are cut off.

As both PAL and NTSC TVs have an aspect of 4:3 and PAL displays more rows, PAL rows appeared "squished" compared to NTSC rows.

On the implementation side: the TIA generates a bitmap of 160xN rows, where N is around 192 or 228 for NTSC and PAL. Of those, take a fixed number (again around 192 and 228), fill any remaining scanlines with black on the bottom, then draw and scale this into a surface of aspect 4:3 -> that's your TV picture.

**Comment by thrust26** [comment]
Correct, except that N has to be larger. Theoretically NTSC can have 486 visible lines (=243 for us) and PAL 576 (=288). Some lines were usually cut off by the TV (due to overscan and centering) and developers usually do not use all lines available. 

The maximum original PAL ROM I found is Acid Drop with 249 lines (from 342 in total). The problem, if we go down to e.g. 250 lines in PAL, they may not center like Acid Drop centered its lines (first line at scanline 54; all details: 54 (VBlank) + 249 (Display) + 39 (Overscan) = 342

For NTSC there are some prototypes which are close to the TV's NTSC/PAL switch over point at ~284. We have to check which games display the most scanlines (maybe this can be automatized?). 

So either 
- we do auto-centering again (nope!) or 
- we allow manual centering for a game (nope!) or
- we allow manual, global centering in TV effects (maybe) or
- we make N even larger, e.g. 260 (maybe)

What would you prefer?

**Comment by thrust26** [comment]
Examples (to be continued):
- Congo Bongo (NTSC) has only 17 lines in overscan.

**Comment by sa666666** [comment]
Implementation-wise, there are two 'textures' here; the initial TIA image, and the resulting image being presented onscreen.  One of them can be smaller or larger than the other.  We have a concept of source rectangle (srcRect), which determines the dimensions of the source (TIA) image.  And we have a destination rectangle (dstRect), which determines how to _scale_ the image into the destination rectangle (aka, the window that you actually see onscreen).

So we (or maybe just me) are getting confused by the two.  I propose that the dstRect is always 320x250.  This emulates our "constant physical sized TV screen".  The main issue here is correctly setting the srcRect so that it contains all the relevant picture details.

Note that are Rect has x, y, w, h.  So we set 'y' according to the starting scanline for the console (__not__ autodetected, but hardcoded), and then 'h' to however many scanlines the TIA generates (this could be autodetected, or again hardcoded according to console type).  Then we simply map the srcRect to the dstRect, and we're done.

This seems to be what @DirtyHairy is saying too.  Is there anything else we need to care about??

**Comment by snes2600** [comment]
Thanks everyone for taking time to explain this carefully for dummies like me!

Stella is the only emulator I've seen to try emulating this part of a TV. And I can think of many other arcade, console, computer emus to bug them about. I can point them here later. :laughing:

**Comment by sa666666** [comment]
I think we've accomplished everything we wanted here, so let's close it.

**Comment by thrust26** [comment]
Yay! 🎆
