### ISSUE TITLE
Empty CPU random setting overwritten by defaults

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#371]
When you clear all flags for "cpurandom" this setting is overwritten by the default value when Stella gets started again.

**Comment by sa666666** [comment]
This is the first time we have an argument where _nothing_ is a valid option.  What's happening is that the c'tor sets the option accordingly (for player, AXYP).  Then, when the settings are loaded, those defaults are overwritten by whatever is read in.

Problem is, the 'nothing' is not being interpreted correctly, so the initial (default) setting is being used.  What needs to happen is that the parsing must take into account an empty string, and assign this to the setting when necessary.

**Comment by thrust26** [comment]
Why did this not happen before?

**Comment by sa666666** [comment]
Because as I said, this is the first time an option can have "nothing" as a valid entry while also having its default set to something.  So in the settings file, we have `plr.cpurandom = `, and in the c'tor `setInternal("plr.cpurandom", AXYP`.  This is the first time that this specific combination has happened.

Fix is in https://github.com/stella-emu/stella/commit/6b760312348c8f293a506aed7972a4b255e5f2d2.  We were excluding settings that don't have a valid key and value, when only the key has to be non-empty; the value _can_ be empty.

**Comment by sa666666** [comment]
Just updated the changelog for this too: https://github.com/stella-emu/stella/commit/72f6096ba84e2b24c35edf914a36109f80be9a48
