### ISSUE TITLE
Phosphor settings clash

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#383]
When enabling Phosphor for all ROMs, two related bugs happen:
- In the `GameInfoDialog` the checkbox for phosphor is disabled
- The blend rate of the ROM is used (even if the phosphor is disabled there)

**Comment by sa666666** [comment]
I think when global phosphor is enabled, the `GameInfoDialog` widgets should just be disabled.  This visually indicates that they are no longer to be used.

Global settings should override per-ROM completely.

**Comment by sa666666** [comment]
That may mean the docs need to be updated :smiling_imp: 

To me, when you select "Phosphor for all ROMs", you are implicitly saying that you are overriding per-ROM settings.  And in that case, you are also overriding the phosphor level too.

So in `VideoDialog`, I would say that the blend level shouldn't even be activated unless "Phosphor for all ROMs" is _also_ activated.  You don't get it both ways; either global phosphor _and_ level is active, or all per-ROM settings are active.  I don't want to make this more complex by mixing global and per-ROM settings.

**Comment by thrust26** [comment]
The docs describe what you say, but the code is (at least partially) different. 

Would there be any user need for the current behavior? That the game blend overwrites the global blend?

**Comment by sa666666** [comment]
And ideally, there should be a dropdown box in `VideoDialog` for this, similar to the one in `AudioDialog` for stereo settings.  To make it clear that when global settings are used, per-ROM are disabled.  Or that when per-ROM is used, global is disabled.

And the disabling of UI widgets will also give a clear visual indication.

If the code doesn't correspond to this but the docs do, then we need to fix the code.  I think the least complex way is what I describe, so that's the direction we should go.

**Comment by thrust26** [comment]
I remember that (after discussing with you) I replaced the drop down box with a checkbox. :smile:

But I think what you suggest with disabling the GameInfoDialog elements makes sense. And then we fix the code that the game specific blend ratio is not used then too.

**Comment by sa666666** [comment]
The other option of course is to have both 'phosphor on/off' and 'phosphor level' _both_ be separate global/per-ROM options.  So instead of two possible variations, we have four.  Not an approach I advocate.

As for the UI, again I leave it to you.  As long as we get the functionality across to the user, I don't care whether it's a checkbox or a dropdown.

**Comment by thrust26** [comment]
IMO we need only two options:
- on by ROM setting (and use ROM blend)
- on by global setting (and use global blend)

Do we really need "off by global setting" (thus overriding ROM settings)? Why would anyone use that?

**Comment by sa666666** [comment]
OK, two is fine.  As long as it's either "all global" or "all per-ROM", as you say.

**Comment by thrust26** [comment]
NOW..., how about the stereo option? Should we align that one and use a checkbox there too?

**Comment by sa666666** [comment]
How will the user know that the checkbox indicates global or not?  And the same question, really, for the phosphor mode?

That's why I initially suggested a dropdown, since the text it the box itself would clearly state whether the option is global or per-ROM.  As long as you can get that information across to the user, I don't care which you pick.  And when you make a decision, yes, both can be aligned to act the same way.

**Comment by sa666666** [comment]
If you have to add more text to the checkbox descriptor to tell what it's doing, you may as well have added it to a dropdown :smiley:

**Comment by thrust26** [comment]
"Phosphor for all ROMs" is not clear enough?

**Comment by sa666666** [comment]
I was talking about the 'Stereo' option.

**Comment by thrust26** [comment]
"Stereo for all ROMs" :smile:

**Comment by sa666666** [comment]
Sure, if that's what you want.  I was just pointing out it needs to be consistent.

**Comment by thrust26** [comment]
Yup. I will take care of it this week.
