### ISSUE TITLE
Input not released after leaving debugger

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#392]
When you enter the debugger while e.g. a switch or the fire button are pressed, these are not released after you leave the debugger. 

So when you e.g. set a breakpoint which reacts on SELECT being pressed, you get into an endless loop of entering and leaving the debugger. Even unticking the SELECT checkbox inside the debugger does not help. 

This did not happen with 5.0.2, but with 5.1.1.

**Comment by sa666666** [comment]
@thrust26, please test the current code and see if this fixes the issue.

**Comment by sa666666** [comment]
Well, it was only being done for a few of the states, and didn't include the debugger state.  I moved the code to the end of the method, so now it clears events for _all_ states.  That's what I meant by saying it needs to be tested, since technically now the behaviour is potentially different for _all_ states that didn't use it before.

**Comment by thrust26** [comment]
Ah, I missed that added line. Now it makes sense. :smile:

**Comment by sa666666** [comment]
I think we can close this one after some testing.  @thrust26, after you test over the next few days, feel free to close it when you're confident that there are no regressions.

**Comment by thrust26** [comment]
I will close this now. If we should find a problem, we can reopen it.
