### ISSUE TITLE
Trace not working for long subroutines

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#393]
Especially when a subroutine takes longer, CTRL+T (trace) very frequently stops somewhere inside that subroutine.

This did not happen with 4.7.2.

**Comment by thrust26** [comment]
Test ROM attached.

BTW: "Run to PC @ current line"  has the identical problem.

[test.zip](https://github.com/stella-emu/stella/files/2597135/test.zip)

**Comment by sa666666** [comment]
Just adding this here since my memory is terrible.

We should implement this by adding a type of breakpoint that is _one-shot_.  That is, it automatically expires once it fires.  Then the above can be re-implemented with such a BP, and the idea of limits on processing time goes away entirely, as would this bug.
