### ISSUE TITLE
Phosphor effect suggestion

### ISSUE THREAD

**Issue by NathanStrum** [stella-emu/stella#395]
Would like to see (as an option) the return of a phosphor mode similar to that from before Stella 5.x. The reason being that when capturing videos (for AtariAge's YouTube site, and for pulling stills for promotional materials), the current phosphor mode doesn't lend itself well to 30 fps capture, and blended frames (while more accurate) don't show flickered sprites cleanly. If the previous version is no longer practical, as an alternative, would be to add an option to specify how many frames the current phosphor effect is held for, so the phosphor intensity could be increased, but the trailing artifacts could be reduced.

**Comment by thrust26** [comment]
Actually the request is to emulate the perception of the eye of a flickering screen into a single screenshot. The eye blends together multiple frames and averages them. 

So for a screenshot I suggest, that, if phosphor is enabled, we take the current and the previous output (**after** phosphor) and simply average them. That way, flickering objects would become a bit darker than not flickering ones, but not as dark as only 50%.

This approach should be quite easy to implement, since we currently have the two screens already for applying phosphor. It should work well for most case cases by far. Only if the flicker rate is lower than 30 Hz, the result might still not be perfect. But fixing that would require buffering additional screens (and the phosphor already helps a bit with that).

**Comment by sa666666** [comment]
Hmm, makes sense.  Do you think we can squeeze it in for 6.0, or should we leave it for 6.1?

**Comment by thrust26** [comment]
After looking into the code, it seems that while applying phosphor, the previous frame gets overwritten. So currently we do **not** have two frames we could blend together. This might take a bit longer...

**Comment by thrust26** [comment]
@NathanStrum Done! Here is how Zookeeper looks now (TV effects and phosphor enabled). 
![zookeeper_20181130_10](https://user-images.githubusercontent.com/24360774/49602186-223b9a00-f988-11e8-826a-6fae79e80af5.png)

**Comment by sa666666** [comment]
My refactoring is done for now.  I may revisit this post-6.0 and attempt to use hardware buffers to do the blending faster.  But that may be more work than it's worth.

@thrust26, you can decide whether to close this or not, if/when you hear back from @NathanStrum.

**Comment by DirtyHairy** [comment]
To chime in, the Stellerator mode mentioned by Thomas is currently available only in Chrome and Firefox (I've disabled it in Safari because of browser bugs) and is called "reduce framerate" (settings page). It reduces the framerate to about 30Hz by merging frames in pairs.

If you enable it, take care to disable POV emulation (also under settings), otherwise, you will get trails for moving objects 😏

**Comment by sa666666** [comment]
Not that this is for 6.0 or anywhere near it, but I wonder what would be involved in adding a similar mode to Stella?  I would only consider it if it's fairly easy to do, since as @thrust26 says, it's really a problem with Youtube, not Stella.

**Comment by sa666666** [comment]
I guess we can leave the issue open for now.  But I really don't think we can have this done for 6.0, or if we will even be able to do it at all.  So unless one of you has a burst of energy to work on this, we should push it to 6.1.  You can decide.

**Comment by DirtyHairy** [comment]
@thrust26 At least that's how I do it in 6502.ts: there's a post-processing pipeline of sorts, after the emulation, and it happens there

**Comment by thrust26** [comment]
Definitely 6.1+

**Comment by thrust26** [comment]
@sa666666 Since we got no feedback from @NathanStrum, I think we can close this one.

**Comment by sa666666** [comment]
I guess if we don't have any feedback, there's nothing else we can do but close it.  If someone responds again, we can re-open and reconsider.
