### ISSUE TITLE
Auto detect controllers

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#408]
Like the bank switching type, we could try to auto detect controllers using byte pattern.

**Comment by sa666666** [comment]
One though up front.  Auto-detect for bankswitch necessarily needs to work on non-instruction boundaries, since with knowing the scheme, we can't know where an instruction starts.  However, we can partition the problem by looking at file size, since there is great correlation between BS scheme and ROM size.  This also helps to eliminate a lot of false positives, since (for example) if a ROM is 16K, there are only so many possible schemes it could be; a large number of them are automatically eliminated.

For controllers, we can't use ROM size at all.  So that means we have the potential for false positives.  However, once we have the BS scheme, we know how to disassemble correctly, and searching for controller signatures can be done on an instruction level, helping to eliminate false positives.

**Comment by sa666666** [comment]
For the latter case above, assuming of course that the static disassembly actually hits the lines of code that correspond to the signature we're searching for.  Otherwise it's all a block of data, and we don't know where the instruction starts.

First thing we should do is collect all ROMs into separate directories based on controller types.  This will make it easier to create test cases.  We can also use the 'check-sig' app in `src/tools`; that's what I use when searching for patterns for BS detection.

**Comment by thrust26** [comment]
Pattern to look for:
- Joystick: INPT4/5 (and |$30 mirrors) 
- Paddles: INPT0..3, not INPT4/5 (and |$30 mirrors)
- Keypad: INPT0..5 (and |$30 mirrors)
- Trackball: most hacks use tables which are different between trackball types

LDA INPT0, X or LDA INPT0|$30, X (b5 08 or b5 38) should cover most two player paddle games. Problem is, that these are only 2 bytes. We will have false positives that way, So we need a combination of positive and negative pattern. Negative pattern for paddles would be LDA INPT4, LDA INPT4,X and BIT INPT4 (and |$30 mirrors).

**Comment by thrust26** [comment]
Runtime detection has its charm. The problem is, that the relevant code might not be executed when the games starts. So we would have to try to disassemble the whole code. Also, we cannot hot-switch controllers yet.

**Comment by sa666666** [comment]
Yep, that's what I meant above by "For the latter case above, assuming of course that the static disassembly actually hits the lines of code that correspond to the signature we're searching for".

Currently, autodetection is being run for 30-60 frames or so anyway, to detect other things.  That may be enough to 'warm the disassembly cache'.  The biggest problem is as you say; the pattern to search for is so short.  Most of the signatures for detecting BS scheme are 3-4 bytes (or more).  And they also rely on ROM size too.  For controller detection, we don't have either of those things, so it makes the problem that much harder.

Still, we should start with collecting all of RomHunters ROMs (about 2000 or so?) into separate directories based on controller type, and work from there.

**Comment by thrust26** [comment]
Almost 1900. Fortunately most non-joystick games are tagged with their controllers.

**Comment by thrust26** [comment]
We could extend the pattern with BPL and BMI.

**Comment by sa666666** [comment]
I have the following ROM statistics (based on RomHunter v15):
- joystick: 1781
- paddles: 83
- keyboard: 33
- driving: 2
- mindlink: 4

Preliminary results for 'check-sig':
- "b5 08" gives 9 hits for paddles, and 16 for joysticks
- "b5 38" gives 29 hits for paddles, and 95 for joysticks

So even with this quick test, not only are we not finding the majority of paddle games, we're finding more false positives for joystick games :disappointed:

**Comment by sa666666** [comment]
"a5 08" and "a5 38" seem to be used a lot too.

**Comment by thrust26** [comment]
Yes, but if you add 10 or 30, the results are getting much better.

**Comment by sa666666** [comment]
OK, I have some ideas, but I have to step away from this for now.  It will become very addicting to get it working, and I __have__ to work on other Stella stuff first.

**Comment by thrust26** [comment]
Hm... Has RetroN 77 priority over Stella now? :wink:

**Comment by thrust26** [comment]
Meanwhile I tested some paddle pattern, results attached. The results are pretty good. Most currently not detected ones have very odd code, which could be used as unique pattern. And the remaining few with false positives are or might be detectable using negative pattern.

[paddles.txt](https://github.com/stella-emu/stella/files/2849376/paddles.txt)
[Paddle_Detect.zip](https://github.com/stella-emu/stella/files/2849377/Paddle_Detect.zip)

**Comment by sa666666** [comment]
R77 over Stella; definitely not.  I just mean when I find time to work on Stella again, it will be with finishing up other older issues, not adding to newly created ones.  The main ones I want to look at are:
- finishing https://github.com/stella-emu/stella/issues/368 and related to that, https://github.com/stella-emu/stella/issues/375
- finally addressing https://github.com/stella-emu/stella/issues/352
- https://github.com/stella-emu/stella/issues/307

These are what I absolutely __want__ finished for 6.1.  The first one you've already made some progress on, but we still need to finish it.  The second one I want done so I can never think about it again.  And the third because it's been requested by Dualcam, and he has donated hardware for me to do it.

**Comment by sa666666** [comment]
Regarding Bumper Bash.  That ROM is odd anyway; I'm still not sure if it's a paddle or joystick game :question:

**Comment by thrust26** [comment]
> Regarding Bumper Bash. That ROM is odd anyway; I'm still not sure if it's a paddle or joystick game ❓

One player, two paddles. :smile:

**Comment by sa666666** [comment]
Are you saying that in all your testing (on all 1900 ROMs), the only false positives you got are the ones listed in the zip file?  Because if that's the case, that's really good.  At some point I'd like to test based on searching the disassembly vs. the entire code.  That will definitely kill some of the false positives.

As for the ones like Mindlink and Compumate, I don't care about those.  They can be hardcoded in the properties database, and it's not like anyone is using these controllers in new homebrews.

**Comment by sa666666** [comment]
Same with BoosterGrip and Driving.  They are pretty esoteric, but I suppose it would be nice if we could get it working there too.  Keyboard/keypad is another question mark.  But realistically, if it could autodetect paddle vs. joystick, that would cover 99% of the ROMs.

**Comment by sa666666** [comment]
BTW, how are you determining these results?  What tools are you using??

**Comment by thrust26** [comment]
I tested against ~1800 joystick games only. There are a lot of false positives for the current Astroblast pattern (which allows joystick or paddle). This one can be enhanced. And one false for Picnic (a negative pattern exists). Sweat seems to be a joystick game, Bumper Bash does not use INPTx. The other ones are using odd and unique code.

**Comment by thrust26** [comment]
> BTW, how are you determining these results? What tools are you using??

I let Total Commander search for Hex pattern. A bit tedious, but good enough for quick checks.

**Comment by thrust26** [comment]
@sa666666 What should the code focus on? There will always be errors, especially with short pattern used for joystick and paddle button detection (trackball and SaveKey are safe).

Currently the code identifies all games which use joystick and paddle buttons as keyboard controlled. Alternatively it could also default to joystick and ignore keyboard controllers.

**Comment by sa666666** [comment]
Whatever causes the least amount of grief in the long run.  Right now, almost 90% of games are using joysticks.  So whatever we come up with, it shouldn't cause joysticks to be mis-detected very often when they constitute 90% of all games.

The fallback should definitely be joystick unless you can conclude with some certainty that it isn't.  I'd rather that the 10% of games occasionally get it wrong than the 90% getting it wrong.

**Comment by sa666666** [comment]
IOW, how often does "joystick buttons **and** paddles" actually mean joystick, and how often does it mean keyboard?

**Comment by thrust26** [comment]
For original games it always means keyboard. And since there are no keyboard homebrews it must be joystick for these.

**Comment by sa666666** [comment]
I leave it to you to decide.  My opinion is, if we can get joystick and paddle auto-detection working, we've covered ~98% of the ROMs out there.  The rest are outliers.  Of course if we can auto-detect others I would be fine with that too.  But I'd rather make sure joystick is correctly detected, even at the expense of the remaining ones.

Long story short; the current approach is assume joystick for everything, and specifically set it otherwise.  In adding this new support, I'd rather we not regress from that too much.

**Comment by thrust26** [comment]
OK, I will remove all code which causes existing joystick ROMs to be detected wrong.

How should we handle the `GameInfoDialog? It has no "Auto" setting like the bankswitching or TV format (instead it defaults to joystick). I think we should align that. Agreed?

**Comment by sa666666** [comment]
Yes, we need an 'Auto' there too, just like elsewhere.

**Comment by thrust26** [comment]
@sa666666 Now that I got the detection working quite reliable, what should we do with the controller settings in Stella.pro? Should I remove those, who are detected automatically?

**Comment by thrust26** [comment]
And another question: Before the new code, the launcher info displayed "JOYSTICK" for all games which had no dedicated controller defined. Now it displays "AUTO". And if we decide to remove the controller settings from Stella.pro, almost all games will display "AUTO". This is not helpful.

Displaying "JOYSTICK" instead of "AUTO" also seems to be no valid solution. 

Maybe we should remove that info and instead use #415?

**Comment by thrust26** [comment]
@sa666666 I think we can close this one now. Agreed?

**Comment by sa666666** [comment]
Since you took the lead on this, I leave it to you to decide.  If you are finished with it, then by all means you can close it.
