### ISSUE TITLE
Simplified option dialogs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#423]
For casual users and consoles (e.g. for R77), Stella's current option dialogs are too detailed and complex. 

The plan is to reduce the available options and put them all onto two dialogs (see also #411):
1. Stella's global options
2. Game specific options

For 1. the following options are considered
UI: 
- Theme

Video:
- ~TIA interpolation~ (TV effects are better here)
- TV mode (no custom mode and settings)
- Scanline settings (only intensity, interpolation is always on)
- (Phosphor for all ROMs)?

Audio:
- Enable sound (might not be required)
- Volume (might not be required)
- (Stereo for all ROMs)?

![image](https://user-images.githubusercontent.com/24360774/55156856-4ac7e980-515b-11e9-9a52-b2c7ca029a3f.png)

For 2. 
- to be discussed, maybe we don't need anything here

**Comment by sa666666** [comment]
We will definitely need something for the game properties.  At least the controllers, since the autodetection you've added is very good, but cannot work 100% (and perhaps never can).   And this is what people are complaining about most with the current community release (incorrect controllers).

NTSC/PAL _could_ be added, but I think the autodetection works almost 100% there.  The same for bankswitch type; autodetection fails very rarely.  In fact, perhaps that's all we need from the game properties, and we don't even need a separate tab for it; just two dropdown boxes for left and right controller.

**Comment by sa666666** [comment]
At some point we may need to consider an event mapping facility.  Doesn't matter for normal controllers, but now that users can add any type of USB controller, along with that comes the desire to change the mapping.

But that's still a long way off, since changes/improvements are needed in the core even for mainline users, before we ever consider introducing a reduced UI for this system.

**Comment by thrust26** [comment]
With auto detection for everything (TV type, bankswitching, controllers), there will be only a very few ROMs failing. And these few can be added to the database. So maybe we could live without game specific settings.

Else:
- Controller settings are needed.
- NTSC/PAL fails for PAL60 games. But usually each PAL60 ROM exists as NTSC version too, so this is probably no big deal.
- Bankswitching can be done via settings or via extension.

**Comment by thrust26** [comment]
Back to the global Stella settings. Do you miss something? Or is something superfluous?

**Comment by sa666666** [comment]
Controller autodetection is very good already,  but still isn't as mature (and well tested) as autodetect for TV type and bankswitching.  The latter we can forget about entirely.  For the former, we need more testing.  But it can probably be extended to be 95+% accurate too.  But until we can get to adequate coverage, I still think we need to offer the option.

For sound, I honestly don't see a use-case for wanting to disable sound.  And if this is hooked up to a TV, volume doesn't seem to be needed either.  In fact, we could also go with stereo sound as default too, since most (all?) TVs released in the past 20+ years are stereo anyway.  Remember, we can still have the options in the settings file, just not have them presented in the UI.

Maybe looking at what AtGames offers WRT end-user settings.  This could give us some guidance on exactly how much configurability we should offer.

**Comment by thrust26** [comment]
Agreed for volume and sound enable. But stereo makes little sense for games which are not designed for it. E.g. the channel for a sound may change randomly.

**Comment by sa666666** [comment]
OK, I have no problem with leaving out stereo sound too.  There are probably only a dozen games that use it, and AFAIK they're all in the database.

Many people using the R77 will also want to try out the latest ARM games, so if controller detection isn't working, then that is a problem.  I think adding the two dropdown boxes for left/right controller is a good compromise.

**Comment by sa666666** [comment]
We can still expose other options in the settings file (and extend `SettingsR77` to do it).  So more advanced users will still have options.

**Comment by thrust26** [comment]
> OK, I have no problem with leaving out stereo sound too. There are probably only a dozen games that use it, and AFAIK they're all in the database.

The stereo option would be for games that are **not** programmed for stereo. So it is just a gimmick which can go.

**Comment by DirtyHairy** [comment]
I think we can skip audio on / off and volume, and also the theme. I would vote for phosphor for all ROMs, though 😏

**Comment by DirtyHairy** [comment]
Oh, and I definitely wouldn‘t enable stereo everywhere. For ROMs with heavy interference effects between the two channels, the result may be very different to the original.

**Comment by thrust26** [comment]
Theme will stay. People like to individualize their programs. :smile:
(more to come probably much later)

This is how it looks now (just one dialog):
![image](https://user-images.githubusercontent.com/24360774/55233678-8fba5180-5229-11e9-9c49-15eeb79e9b30.png)

**Comment by thrust26** [comment]
BTW: How about a user friendly way to provide logs for us? Handling files is a problem for many people today, so maybe we should add a (the existing?) logging dialog? So that people can take screenshots.

**Comment by thrust26** [comment]
This can be closed now.
