### ISSUE TITLE
Scanline artifacts

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#425]
In certain cases (Windows, odd zoom level, no software rendering, no scanline interpolation), the scanline emulation creates hefty, unwanted artifacts since Stella 5.0.

![Pitfall! (1982) (Activision)](https://user-images.githubusercontent.com/24360774/55461607-2786b980-55f5-11e9-80d9-f3303bf092ce.png)

**Comment by thrust26** [comment]
BTW: In software mode, it seems like scanline interpolation might be always enabled.

**Comment by sa666666** [comment]
TBH, I don't consider software mode a valid one.  I do no testing there, and it's basically only there because SDL2 offers such a mode.  Going forward, I wouldn't be surprised if SDL kills software mode completely, and goes strictly with hardware rendering.

As for the scanline interpolation, yes, that is typically only implemented in hardware, so only those modes would honour the setting and use it.

**Comment by sa666666** [comment]
To me this seems to be an overflow horizontally.  Almost as if the scanline texture is too wide, and spilling into the buffer (ie, onto the next line(s)).

**Comment by thrust26** [comment]
Removed option to disable scanline interpolation which removes all artifacts.
