### ISSUE TITLE
Conflicting Compumate keys

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#490]
Some CompuMate keys conflict with default Stella keys:
- T (Time Machine)
- Backspace (Fry)

Especially the latter is pretty annoying (if anyone should ever seriously play with the CompuMate). How should we handle that? 

Maybe we should add modifier keys. That would also prevent unwanted frying.

**Comment by sa666666** [comment]
This didn't happen before the recent mapping rework, so there must have been a method or something that disabled input in Compumate mode.  The only key that was allowed (from remapping) was Exit (Escape).

**Comment by sa666666** [comment]
I think the best thing to do is detect when Compumate is active, and only allow 'Exit' to be used.  All other keys should be sent directly to Compumate.

**Comment by sa666666** [comment]
This worked up until github.com/stella-emu/stella/commit/b566c34793b56db485db48109dd4ca7aededcee1.  After that, Backspace is interpreted differently.  So that's the place to look I guess.

**Comment by sa666666** [comment]
Another option is to somehow have a virtual method on `Controller` (or elsewhere) that acts as a "key mask", and returns true if the class will 'own' the key combo (and hence it must be passed to it without remapping), or returns false otherwise (in which case it is passed to the remapping subsystem and acts as normal).

For all controllers other than `Compumate`, it will return false.  For `Compumate`, it will return true if an internal map says that the key-combo is needed directly.  This way, only `Compumate` pays the price for the mask, and for all other cases it's a simple virtual method call.

Or maybe that functionality can be embedded directly in `PKeyHandler`, and another 'group' created for 'Compumate'.

**Comment by sa666666** [comment]
Basically, have a group (a map) in `PKeyboardHandler` that, on each call for mapping, checks whether Compumate is active.  If so, and the map contains a key that Compumate needs, do not do any remapping at all, simply return it.  Otherwise proceed as normal.

IOW, only enable remapping when not in Compumate mode __and__ the key isn't needed by Compumate.  Compumate is a special case that needs to bypass remapping for the most part.

**Comment by sa666666** [comment]
Consider `EventHandler::setState`, in the block for TIA mode:
```
    case EventHandlerState::EMULATION:
      myOSystem.sound().mute(false);
      enableTextEvents(false);
      if(myOSystem.console().leftController().type() == Controller::Type::CompuMate)
        myPKeyHandler->useModKeys() = false;
      break;
```
That's the perfect place to put a call to `myPKeyHandler->useCompumate()` (or whatever you want to call it), to set a flag that `Compumate` is in use.  Then in `PKeyboardHandler`, each time the core requests to get an event for some key, check this flag.  If the flag is set and the key-combo is needed by `Compumate`, do not remap it.  Otherwise do, as normal.

**Comment by sa666666** [comment]
Will I do this, or do you want to look into it??

**Comment by thrust26** [comment]
I will look into it.
