### ISSUE TITLE
(Libretro) Build failures OSX/iOS

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#555]
iOS -

http://paste.libretro.com/182254

OSX -

http://paste.libretro.com/182253

**Comment by sa666666** [comment]
These 'errors' are all valid C++14 code.  The build scripts also say to use C++14, so the compilers must be at fault here.  I suggest looking into making sure your compilers are actually C++14-compliant.  This will become more of an issue in the future once we move to more C++14 features.

**Comment by twinaphex** [comment]
It isn't just this - 

Windows (x86) fails now too -

http://paste.libretro.com/182329

Can Travis build jobs be set up to test every commit perhaps for the various Libretro targets? This could perhaps prevent these compilation errors continually happening in the future.

Pretty sure that the Mingw toolchains on our buildbot are as up to date as possible.

**Comment by thrust26** [comment]
The `Lightgun` was added by me just yesterday. I just added it to the libretro makefile.

**Comment by thrust26** [comment]
@sa666666 Is there way to automatize this? Or at least a list of files which have to be fixed when the structure of the project changes?

**Comment by twinaphex** [comment]
It's just a suggestion from me, but all of our other Libretro cores don't use Visual Studio solution files. Instead, we build MSVC libretro cores with the regular Makefile (see all the elaborate rules in Makefile.libretro files). This way, we only need to update Makefile.common, and no other files.

This might be a far more pragmatic model of development vs. having to manually update a separate vcxproj file every time.

**Comment by thrust26** [comment]
If so, why is there are VS project file in the libretro folder? Can this be removed?

**Comment by twinaphex** [comment]
I don't know, this core was made by upstream. The only version we maintain is the 2014 older version.

**Comment by twinaphex** [comment]
libnx/switch is fixed now at least, and OSX/iOS build now again too.

**Comment by thrust26** [comment]
So`, can this be closed or not?

**Comment by sa666666** [comment]
Regarding the different build environment configurations.  For most of Stella's lifetime, there were only really Windows, Linux and MacOS being maintained.  So it was easy for me to just maintain all 3 of them myself.  Now that Stella is being ported to many different platforms again, it will get harder to sync all the environments.  But I wonder if we can justify unifying all the build environments, since really, how often are we adding or removing files??

Regarding the libretro VS project file, I don't think RetroArch uses it, but maybe someone wants to work on RetroArch on Windows.  So they would need a VS project.  It is there, and working for now, so I say leave it alone for now.  After we do a proper 6.1 release, we'll see how many people are actually interested in working on the RetroArch port and then reconsider whether it's worth keeping.

Finally, regarding the C++ issues.  Stella currently requires C++14 with threading support.  Going forward, I will be making heavier use of C++14, and perhaps in a year or two even moving to C++17.  We don't have the manpower to move the newer standards and keep compatibility with older ones.  So if a compiler/environment doesn't support what we're using, then it will have to be left behind.

OK, so unless anyone else has something to say, we can close this one.

**Comment by trioan** [comment]
As a libretro user, it's great having updates with mainstream compared to earlier when we were stuck with 2014. Thank you for that!

When the devs switch to C++17, that should kill more libretro platforms. Those compilers won't be getting updates that far, and you're going to get non-fixable bug reports. You're already getting a small flood of non-compliant C++14 compiler fixes.

It might be worth chopping the libretro portion (later) to avoid that headache. Thank you for everything so far!

There's other libretro problems but that's not for this thread.

**Comment by trioan** [comment]
Libretro buildbot is working correctly, so it's not failing.
http://buildbot.libretro.com/nightly/apple/ios/latest/
http://buildbot.libretro.com/nightly/apple/ios9/latest/
http://buildbot.libretro.com/nightly/apple/osx/x86_64/latest/

**Comment by twinaphex** [comment]
Let's close this for now yeah. Issue seems resolved for now.
