### ISSUE TITLE
Allow gradual scaling of ROM info 

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#580]
Currently we are limited to 1x or 2x, fractional zoom values are more flexible. 

Also the UI dialog would be changed then, so that the user can decide how much space (%) he wants to reserve for the right launcher side.

**Comment by sa666666** [comment]
@thrust26, in designing this, I need to know the allowable range of scaling, and at what interval.  I suggest changing `romviewer` setting to be a double instead of an int, and the allowable range to be from 1.0 to 2.0, with 0 meaning 'off' (to match the old setting).  Will we increment in blocks of 0.25 or 0.5?  Or would you rather have more fine-grained intervals??

Whatever we decide, I think the range itself should be from 1x - 2x.  Otherwise it complicates some coding.

**Comment by thrust26** [comment]
I plan no range, but a percentage. The percentage would theoretically be between 0 and 100% (in 1% steps). But I would limit the latter, so that the ROM listing doesn't become invisible. 

We can convert any range into a percentage and vice versa. But UI and command line parameter should be percentages. That is much easier to understand for the user.

**Comment by sa666666** [comment]
OK, but I need to work with an upper and lower range.  So how about a range of 100% to 200% maps to 1x - 2x, and 0 means 'off'.  Technically, it doesn't matter to me either what the increments are in absolute terms, as long as a I know what 100% and 200% mean, and that the increases are linear over the entire range.

**Comment by sa666666** [comment]
To be clear, I don't want the percentage to be of the window width, but of the image width.  That's the way the current code works, and it's much easier to keep it that way.  So we can show images from 1x up to 2x, in whatever increment you like.  How you display that in the UI is up to you.

**Comment by thrust26** [comment]
Then the range should be floating number from 0x to unlimited.

**Comment by sa666666** [comment]
The image size is not relevant here, since whatever we set it to, the scaling will work.  But I still need an absolute minimum and maximum width (in pixels) to determine if it's too large for the current window, and what size font to use.  I'm concerned with creating the space in the UI for the image and text.  The scaling will take care of 'fitting' it; I want to make sure the UI area is the correct size.

I think we're talking about the same thing, just coming from different directions.  I would like to have a known minimum and maximum limit.  So currently, 1x mode means 365 pixels wide, and 2x mode means 660 pixels wide.  We can't really go below 365, since then there's not enough room for the text.  And we have to be careful of the upper limit too, since it might be too large for the ROM launcher dimensions.

Really, I want the minimum of 365, and that should map to the lowest percentage, however you define percentages.  The upper limit can be 660, or it can be unlimited.  But then, how do you display a percentage for an unlimited width?

This is why I suggested having the actual 'x' times be specified for the images.  We do it for TIA zoom levels, so it makes sense here too.  So 100% means 1x image zoom (and hence 365 pixels), and it can go up from there, perhaps to a limit of 3/4 the size of the entire window.

**Comment by thrust26** [comment]
> But then, how do you display a percentage for an unlimited width?

You asked about a range which seems to be a scale factor based on something. 😄 

The minimum can be smaller than 365, because then we have a lot of vertical space for the info text. Which can wrap around to multiple lines. So there is no reason for 365. In the UI, the lowest percentage would be 0 (= off). Even 1% would work, we just have to make sure that the info text display stops early enough. Off course 1% makes little sense for the user. But depending on the launcher size, the lowest usable percentage will vary. That's why I would not want to limit it.

And the upper limit would be theoretically 100%. This can also become quite large, for the same reasons as for the lower limit. So I would not want to limit that one too. 

If you insist on a limit, then it would be between ~10 and ~90% of the launcher size. 

IMO part of the problem is, that you want to keep using a range. It makes things complicated and is a legacy remainder. Why can't we switch to using percentages? We have the launcher size and from that we can easily calculate the ROM info widget width using the percentage.

**Comment by sa666666** [comment]
I will experiment with using a percentage of the total window size, and restrict to 10% - 90% for now.  My reason for wanting to use a range (if you can call it a _want_) is that's how the current code works.  I can change just 4 lines of code to get non-integral scaling from 1x - 2x.  Going to percentages means a larger reworking.  I will work on it some more.

**Comment by thrust26** [comment]
It your time is too limited, I can take over. Just let me know, please.

**Comment by sa666666** [comment]
No, not lack of time right now.  Just general programmer 'laziness', where I try to get the end result with as few changes as possible :smiling_imp:

**Comment by thrust26** [comment]
Oh, that's a problem. I am currently not lazy and very motivated for the optimal solution. 😈

**Comment by sa666666** [comment]
Recovering from a cold, I guess that kills some enthusiasm.  But I will get it done.

**Comment by thrust26** [comment]
Almost done with a891887 and 0385611. 

ToDo: Select zoom level for R77 (currently 2.0)
