### ISSUE TITLE
'saveconfig' not possible

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#602]
The file is not writeable (Windows).

**Comment by thrust26** [comment]
Currently the path of the configuration file is the path of the ROM. For other save actions it is the default save dir. The former is not always accessible.

**Comment by sa666666** [comment]
I think this is actually a bug, since I tried it on a ROM dir that is definitely writable and get the same error.

As for the case where the ROM dir is NOT writable, I think this was already discussed in issue https://github.com/stella-emu/stella/issues/352.  We decided to have the config files in the same location as the ROM.  If we allow to save them to the default path, then what happens when there is a cfg file in the ROM dir (not writable) and also in the default save dir (writable).  Do we do something different on load and save, or try to accommodate both, etc?  This was exactly the source of that issue, and why the code got so unwieldy (there were some files that had up to 4 possible locations that had to be tested!).

I _**really**_ don't want to go there again.

**Comment by thrust26** [comment]
Of course there should be only one directory which has to be tested. Which one that is I don't care. 

But it should be writable. 😉

**Comment by sa666666** [comment]
OK, we decided to have the cfg files with the ROM.  If we can read them from there, that is fine.  But if we can't write there, then we have to save to default dir.  So now we have extra work:

- For saving: attempt to save to ROM dir, and if that doesn't work, then save to default dir.
- For loading: attempt to load from ROM dir, and if not found then attempt to load from default dir.

So already we have multiple paths to test.  Now, what happens when ROM dir isn't writable, but it contains a cfg file?  We can load from there, but have to save to default dir.  Then later, when loading the ROM again, it won't pick up any changes, since it always goes back to the cfg file in the ROM dir!

So we instead make the default save dir be the 'default' load/save dir for cfg files.  But that clutters our default save directory, which is often in a public place.  And if we go the old route of having a 'cfg' dir in Stella base folder, then we run into issues of people not finding it, because it's often hidden!!!

Like I said, this was exactly the cause of the aforementioned issue.  And we went round and round, and never did resolve it in all cases.  We decided that the cfg files would be associated with the ROMs directly, and if you need to modify them, then the ROM needs to be placed in a writable location.  Any other option, and we get into the madness of https://github.com/stella-emu/stella/issues/352 again :unamused:

**Comment by thrust26** [comment]
Hm... I thought we had solved these problems too.

> So we instead make the default save dir be the 'default' load/save dir for cfg files. But that clutters our default save directory, which is often in a public place. And if we go the old route of having a 'cfg' dir in Stella base folder, then we run into issues of people not finding it, because it's often hidden!!!

One of these two is IMO the least bad solution here. 
- E.g. disasms are saved on my Desktop. Not nice and it clutters the desktop, but at least consistent. - When I can use a debugger, I can find config files too (especially if we display the path in the debugger) in hidden folders.

I tend towards the latter, but I will leave it up to you to decide.

**Comment by sa666666** [comment]
OK, but we still need to deal with the case where a file is saved in one place, and loaded from another.  Since one would expect that when you save a file and later open the debugger, it will use the most recently saved one.

The only way to do this, without going through testing lots of locations is having the cfg file loaded _and_ saved to the same place.

And there are two options for that, in which I only want to do one (since otherwise we're complicating the code again):
- Load/save the cfg file in the ROM dir, and if the ROM dir isn't writable, then just generate an error indicating that.  The user can then move the ROM to a writable directory to work on it.
- Load/save the cfg file to a 'cfg' folder in Stella base folder.  This will always be writable, but we lose the close association ROM and cfg file, and it's in a hidden dir.

The first one is what we do now (barring the bug that I have to fix).  We can move back to the second one, which is what Stella did before.  But I only want to implement one of them.

**Comment by thrust26** [comment]
I am for the latter.

**Comment by sa666666** [comment]
OK, then it is decided.  I will get to it later this evening.
