### ISSUE TITLE
Provide info with ROMs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#603]
Currently Stella tries to auto detect several settings. But not everything can be detected. For known ROMs Stella has a built-in database. For others the user can define the settings via GameInfoDialog. These are persisted in a common Stella.pro file.

However we are missing the option to provide a ROM together with the necessary settings info. Discussed solutions are:
1. Encode info in a header
2. Encode info in the ROM filename
3. Have a separate file alongside the ROM, containing the info we need, sort of like a header, but not in the ROM itself
4. Make use of some bits that aren't normally used in a ROM

Option #3 seems the best one to me, given the current situation. We could use the existing .pro structure for this. It would be good if ROM and .pro file could be read from a ZIP archive.

For discussion see this thread:
https://atariage.com/forums/topic/304424-support-of-header-rom-files/

**Comment by andrew-davie** [comment]
Is it completely out of the question to auto-detect?  As a thought-experiment, say with an unknown ROM Stella tried every one of the bankswitch schemes. Only a small number of those will have stable frames for any length of time, right?  Some number approaching 1.

**Comment by thrust26** [comment]
Stella auto detects bankswitching already by static code analysis.

**Comment by sa666666** [comment]
Autodetection of bankswitch scheme is already quite robust.  And you can also change the filename extension to force a specific type.

Autodetection of NTSC/PAL is very robust.  The only issue is PAL60, which is detected as NTSC.  But with Stella 6.1, you can add 'PAL60' (or variants) to the filename to force that as well.

Autodetection of controllers is quite good, but there are some cases that we'll never be able to detect.

I think having a properties file alongside the ROM (or in the same ZIP file), named the same as the ROM but with a '.pro' extension, will satisfy all needs.

**Comment by sa666666** [comment]
Just in case it wasn't clear, I plan to go with option 3.  And @SpiceWare on AtariAge even reminded me that Stella used to do such a thing, back in the pre-1.0 days.  So we're coming full circle :smile:

**Comment by sa666666** [comment]
This is now implemented in https://github.com/stella-emu/stella/commit/becc72e3ea2b23ede4e95129dcb8e4551b447659.  Still TODO is use the pro file if it's in a ZIP file next to the ROM.  So I'll leave the issue open until that part is done.

**Comment by sa666666** [comment]
I will bump the ZIP part of this to 6.3.  We'll see how many people actually use this functionality.

**Comment by ale-79** [comment]
The manual needs to be updated:
I tried writing a .pro file and couldn't get it to work until I realized that the properties' names  have been sligthly changed compared to what's in the docs:
e.g. you need to use "Cart.Name" instead of "Cartridge.Name", "Console.TVType" instead of "Console.TelevisionType", etc.

**Comment by sa666666** [comment]
Yep, forgot to update the docs.  Also, the intent was to have a button in the **Game Properties** dialog to save this directly from Stella.  The intent was never to have to write a properties file yourself (although of course you can if you want).  So I will get that done for the next release too.

**Comment by thrust26** [comment]
Currently Stella is saving properties automatically. Why would be need a button for it?

**Comment by sa666666** [comment]
To save properties for just the currently loaded game only into a standalone .pro file.  Basically to create the file that this issue is meant to use, instead of having to create it manually, as @ale-79 was trying to do.

**Comment by sa666666** [comment]
I think the use case for this is as follows:
- A developer wants to release a test build of a ROM that needs custom properties set
- They don't want to force the user to have to set them
- So they set the properties in Stella, save a custom .pro file for that ROM, and then distribute that .pro file with the ROM
- So in the end, we get the functionaliity of a ROM header, without the disadvantages listed at the top of this issue.

It makes no sense to force the developer to write this file manually, when the functionality is already in Stella, and just needs a button to expose it.

**Comment by ale-79** [comment]
I use a bash script to build different versions of a rom at once by passing parameters to dasm, and I was thinking that I could also generate the property files automatically, that's why I was experimenting by writing one manually.

In fact, instead of creating the file from scratch, the script would only need to replace/create the line with the md5sum each time I modify the code, the rest is always the same and can be created once with the "save" button, when it will be implemented (for now, I can simply set the properties in Stella and copy and paste the block from the global "stella.pro")

**Comment by sa666666** [comment]
The button would be for developers that don't necessarily know how (or care) to write scripts, etc.  Personally, I could write it manually too, but it's so much easier to just click a button sometimes :)

**Comment by thrust26** [comment]
But Stella is creating a common stella.pro file already. So you want that button only for creating individual files?

**Comment by sa666666** [comment]
Yes, but that common `stella.pro` file can potentially have 100's of entries.  The whole point of this issue is to replicate the behaviour of the ROM having a header, and as such, having (a) a properties file that is named after the ROM, and (b) contains only information for that ROM.

The alternative is to save to `stella.pro`, open that file in a text editor, search for the appropriate entry, copy it to a new file, and make sure to save the new file with exactly the same name as the ROM.  Of course none of that is particularly difficult to do, but why go through the work at all when we can have a button there to do it all, deterministically and without error?

**Comment by thrust26** [comment]
Makes sense. 

Put the Save button right of the Default button, please.

**Comment by sa666666** [comment]
Easy enough to do.  As this is your area, any opinion on what the button text should be?

**Comment by thrust26** [comment]
The text should tell the user that he creates a custom property file. But there is not a lot of space. Maybe we have to accept something generic like "Save"? Or do you have a good idea?

**Comment by sa666666** [comment]
I was thinking "Save" as well.  I guess it will need to be documented as to its actual function.  Is "Save Custom" too long (or too confusing)?

**Comment by thrust26** [comment]
I wouldn't understand that any better than "Save". :smile:

**Comment by sa666666** [comment]
Well, if it doesn't help in understanding, there's no point in doing it.  For now I will just put "Save" there; we can always change it later.

**Comment by sa666666** [comment]
A popup that temporarily appears when you hover over a UI item is also a possibility.  I have an idea of how to implement it, but don't know all the gotcha's unless I try it.

**Comment by thrust26** [comment]
A mouse over? That would be cool. But it wouldn't help if people navigate with the keyboard (or joystick).

**Comment by sa666666** [comment]
No, it would only help people using a mouse.  But even in a standard UI, you only get tooltip hints with a mouse too, I think?

The infrastructure is all there.  A popup widget already exists; in fact a ContextMenu is simply a popup triggered by RMB click.  We register mouse enter/exit events (to change colours).  About the only complication would be timers, so that the popup is triggered only after a certain amount of time, and goes away after a certain amount of time.  It's all there, just a matter of putting it together.  In fact, there may even already be an issue for this 😈

**Comment by thrust26** [comment]
> In fact, there may even already be an issue for this 😈

I remember that I created something some years ago. :smile:

**Comment by sa666666** [comment]
Yep: https://github.com/stella-emu/stella/issues/171

**Comment by sa666666** [comment]
> Put the Save button right of the Default button, please.

Unfortunately, that is going to be difficult.  The Default/OK/Cancel buttons are all created together, in the `Dialog` class.  Putting a button in between them is not how the current code was designed.  In fact, the only thing in that area is either _Default/OK/Cancel_ or _OK/Cancel_.  I'm not sure how to add an option for this, other than hacking in support for it.  But I'd like to make it more general than that.

**Comment by sa666666** [comment]
Loading a properties file from a ZIP file containing the ROM is now supported, so this can be closed.
