### ISSUE TITLE
Request: independent position for game view, debugger view

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#615]
When I trigger the debugger ('), the top left corner of the debugger window is the same as the normal game window that I was just watching. If I move the debugger window to top left of my screen (it's almost full-screen size so I need to do this), and then [EXIT] then the game window has also moved to top left. This is not deisrable. I'd love to be able to position the game window somewhere else, and then trigger the debugger (top left) and then go back to game (say, middle-ish).
They're currently tied together, which is a bit of a pain, as I have to reposition the debugger every time I use it.

**Comment by thrust26** [comment]
Better windows handling (also on multiple monitors see #181 and #531) is an ongoing topic. Whenever time permits we will come back to it.

**Comment by thrust26** [comment]
@sa666666 I just looked into the code. It is very much tailored to one single surface only and doesn't know which surface it is currently destroying or creating. I will either pass through that info, so that we can preserve window position and display separately or make the individual entities take care of it.

But wouldn't it make more sense to create individual surfaces for launcher, emulator and debugger?  IIRC we talked about that lately.
