### ISSUE TITLE
Discussion/Request - trigger speed mode

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#621]
With Thomas's recent addition to allow toggling of "speedup" which was used to demo the Chess program on ZPH's show... I was wondering if it might be possible to trigger on/off this mode from the program side. That is, rather than rely on the human to turn it on when chess is thinking, and off when not - would it be possible for stella to monitor some address/value combination that would trigger from the program side. This would be super-cool!

**Comment by thrust26** [comment]
Actually I don't like that idea. Stella is an emulator and IMO we shouldn't let ROMs manipulate the emulation. Also, if we start here, there are plenty of potential options (e.g. taking screenshots, saving the state, enter the debugger etc. pp). So where does this stop?

If any, we could enhance the debugger. So that it can trigger such actions in general based on the usual conditions.

**Comment by thrust26** [comment]
See #626 instead.
