### ISSUE TITLE
Crash on loading ROM (romBankCount is 0)

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#653]
The attached ROM crashes on line 201 of `CartEnhanced.cxx`, due to trying to do mod of 0.
```
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
bool CartridgeEnhanced::bank(uInt16 bank, uInt16 segment)
{
  if(bankLocked()) return false;

  const uInt16 segmentOffset = segment << myBankShift;

  if(myRamBankCount == 0 || bank < romBankCount())
  {
    // Setup ROM bank
    const uInt16 romBank = bank % romBankCount();
```
It seems that `romBankCount()` is 0, so doing `bank % 0` gives a floating point exception.  I'm not sure where in the code this is being caused, but I would think `romBankCount()` should always be at least 1.

[anim.zip](https://github.com/stella-emu/stella/files/4737000/anim.zip)

**Comment by thrust26** [comment]
The ROM is 4094 bytes. I am pretty sure that's the problem (and the fix is easy).  

@sa666666 Is that size legal?

**Comment by sa666666** [comment]
Sorry, I didn't look at the size.  Technically that size is not legal, but it did work in older versions of Stella.  So we could either fix it in your code, or display an error message that the ROM is an invalid size.  In any event, Stella shouldn't just crash.

**Comment by thrust26** [comment]
Agreed. I think I will first harden my code.

**Comment by thrust26** [comment]
This case is fixed. After the major refactoring there might be some more odd cases.

**Comment by andrew-davie** [comment]
I would like some consistency here. I had a similar issue on 3E+ and the solution there appears to be that my ROM was an invalid size.  Or more to the point, the official "spec" of the bankswitching scheme would be rewritten to make it illegal, and by inference I would have to change what I'm doing. Even though the alternate - a "fix" was a simple one.

I certainly don't want binaries I have released to not run on future versions of Stella.

Along these lines - what is a "legal" size, anyway?  Powers of 2?  Multiples of 1K?  2K?  4K? Something that is explicity (and retroactively) applied to the definitions of bankswitch schemes?

I just think it would be useful to consider these things.

Perhaps all bankswitch schemes could have a "virtual" binary footprint of the defined "legal" size, into which a binary is loaded. Thus, stella would be happy with enforcing particular code/size boundaries, but the binaries would still be OK if odd-sizes.  In particular the various "modulus" functions would be OK on the (current) truncating rather than rounding-up that is required by odd size binaries.

**Comment by thrust26** [comment]
Generally I would consider everything that runs on real hardware as legal. 

Now, if you have a bankswitched cart with two banks which always starts in the 1st bank. Then theoretically the 2nd bank could be any size between one and bank size. And as long as you stay on the 1st bank, everything is fine. But then, what happens when you switch to the 2nd bank outside its size? What would a 2600 "see" there? There has to be something. 

So, what could Stella return there?
- 0 bytes
- random bytes?
- whatever is on the bus?
- repeated bytes from 2nd bank?
- bytes from 1st bank?
- ...?

IMO none of these really make sense. Therefore I would suggest that only full banks are accepted and the Stella returns an error when loading an incomplete ROM.

**Comment by andrew-davie** [comment]
I would expect a program accessing ROM outside of the bounds for which it is written... to crash.
Of your options, I would take random bytes (floating BUS). 
But the point is, just because a ROM isn't a "standard" size doesn't mean it will be accessing invalid addresses. In fact it is pretty much certain that the code will only access valid addresses.
So as a first reaction - your concerns here are unwarranted. You're posing a problem that is indicative of a faulty ROM.  That is, access outside of bounds.
But in any case, my suggestion of a "virtual" address space which is "standard" size into which the ROM binary is loaded would totally fix this. You'd then be returning zero, which would make absolutely no difference anyway. A faulty ROM accessing outside of bounds... who cares how you handle it - program should crash.

**Comment by thrust26** [comment]
Can you elaborate your "virtual address space/binary footprint", please? I am not sure if I get your idea.

Are you saying that Stella should round up the ROM size to the next valid boundary? Which would be what? The bank size? A power of 2? 

What should be read from that extended size?

**Comment by andrew-davie** [comment]
> Can you elaborate your "virtual address space/binary footprint", please? I am not sure if I get your idea.
> 
> Are you saying that Stella should round up the ROM size to the next valid boundary? Which would be what? The bank size? A power of 2?
> 
> What should be read from that extended size?

Yes, pretty much.
Whatever the ROM size is expected to be by stella, then stella first creates a buffer of that size. And then fills with zero, or random, or whatever. And then loads the binary into that buffer. This way, any calculations regarding banks will be correct - because Stella will now have "correct" ROM/buffer sizes.  In other words, it's a method to "fix" bad rom sizes without having to say "we simply can't/won't run this binary because it's the wrong size".
And again, I don't think it matters what should be read from the "extended size". If the ROM is using it, then it is faulty.
