### ISSUE TITLE
Libretro Stella core now on Steam

### ISSUE THREAD

**Issue by twinaphex** [stella-emu/stella#659]
Hi there guys,

sorry for opening this as an issue, which it isn't, but I thought we had something which you guys might like to learn.

a while ago I asked for consent on publishing Stella as a free DLC core for the upcoming Steam RetroArch. You guys agreed back then and it has been a while.

So I think you will be glad to see that we finally got it past approval!

https://store.steampowered.com/app/1227443/RetroArch__Stella/

@hizzlekizzle wrote the descriptions and such and had to go to great pains to write everything in a way that respects Steam TOS (no mentions of companies, commercial games or systems). That being said, in case there's anything you guys would like to see posted on there (assuming it doesn't fall foul of Steam TOS), don't hesitate to contact @hizzlekizzle.

And as previously stated, our commitment is that this release will be fully free, no strings attached. We hope that with this move, Stella will start getting some much-needed recognition on the main stage.

Feel free to close this issue since it's not an issue.

NOTE: RetroArch is not on Steam yet. We are first getting 11 handpicked cores past approval, publishing those  and then launching RetroArch itself. We will then do a further trickle down of cores after that point. So Stella is part of that initial launch window.

**Comment by sa666666** [comment]
Thanks for the update.  Everything looks fine on the Steam site, but I have one request for the info on https://docs.libretro.com/library/stella.  Please change all occurrences of "Eckhard Stolberg" and "Brian Watson" to **"Thomas Jentzsch"** and **"Christian Speckner"**.  Perhaps do a global search/replace to make sure you have all instances covered.

I'd like this done to acknowledge the huge improvements over the past 3 years are in large part due to these two guys.  And if Stella is going to become more mainstream and people will be looking at the authors, I'd like it to accurately reflect that fact.

**Comment by twinaphex** [comment]
I'll let @hizzlekizzle know, thanks.

**Comment by hizzlekizzle** [comment]
Alright, got that changed in the docs :)

**Comment by sa666666** [comment]
Hmm, still shows the old names in the link I provided above.

**Comment by sa666666** [comment]
Nevermind; I guess the page took some time to update.  Thanks for updating the info.

**Comment by twinaphex** [comment]
Hi there guys, just as an update on this -

RetroArch finally went live on Steam yesterday - and everyone can now download RetroArch and the Stella core on Steam. It's part of the first batch of cores to be released.

https://store.steampowered.com/app/1118310/RetroArch/

https://store.steampowered.com/app/1227443/RetroArch__Stella/

Hope this brings with it an influx of users and good positive attention for your project!
