### ISSUE TITLE
zoom lower limit

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#665]
Is the "zoom" setting 200% lower limit adjustable? 
I'd love to be able to render to a smaller window.

**Comment by sa666666** [comment]
No, as the UI takes a certain amount of space that we can't go below.  So 640x480 (aka, 200% zoom() is the smallest we can have.

**Comment by andrew-davie** [comment]
OK, that's a shame.
Might I suggest that the "200%" is misleading, then?
Shouldn't the minimum size be called "100%"?
It's like having a volume knob that starts at "2", not "1".

**Comment by sa666666** [comment]
The 200% is an implementation detail that probably shouldn't have been exposed.  However, the base size is 320x240.  So 300% is 3 times that amount.  If we normalize the smallest one to 640x480, then 3x is no longer accurate either.  Basically, those sizes are with respect to the base size.

**Comment by andrew-davie** [comment]
Technically, I almost never use the UI.
So, as a lateral suggestion -- allow 100%, but switch to 200% if UI is displayed - and then back to the previous % when UI is closed?  It seems a shame to have to abandon 100% for the UI when it's 99% of the time never actually seen.
Also as a separate issue - can't you apply post-rendering scaling to the rendered buffer (with UI present if applicable) and allow the user to scale the window to any size they want?

**Comment by thrust26** [comment]
I tested smaller zooms when I implemented the font option for the UI. 175% should work with the smallest font. But something failed and I cannot remember what.

**Comment by sa666666** [comment]
If we don't display the UI, then yes, the TIA window could be set to 100%.  It would require some refactoring in a few places, since the assumption is a minimum window size of 640x480.  But it is doable.

Post-processing effects (aka, Blargg TV effects) require a minimum width of 568.  This is how the Blargg code is written, and there's no way around that.  So the decision was made to make the TIA be minimum of 640x480, so the TV effects would always work.  Downsampling such a buffer to 320x240 looked horrible.

Regarding the in-game UI, yes, that could be downsampled too.  But unless it's at an integer scaling factor, the fonts become unreadable.

In the end, we decided it was easier to bypass all these issues and simply make the minimum window size be 640x480.  I suppose it might be possible to have a 100% window size with severe restrictions:
- it would be off by default
- the in-game UI would either not be present, or it would be scaled to 50%
- Blargg TV effects would not be available

How often is this use case relevant?  Can we justify the work it will take to implement it??

**Comment by andrew-davie** [comment]
> How often is this use case relevant? Can we justify the work it will take to implement it??

Well, I would **always** use the smaller screen myself.
In answer to the second question... "No",  but thank you or the explanation/reply.

**Comment by thrust26** [comment]
Get yourself a high DPI display and then you have the same effect. :wink:

**Comment by andrew-davie** [comment]
> Get yourself a high DPI display and then you have the same effect. 😉

The only computer I own/use for programming is a MacBook. The stella window is unfortunately big on this display, hence my original question.

**Comment by andrew-davie** [comment]
Just a comment to show minimum window size on my display... I'm not pushing for this - happy for it to be closed.

<img width="1280" alt="Screen Shot 2020-06-14 at 12 16 47 am" src="https://user-images.githubusercontent.com/16424075/84571063-6eb13280-add4-11ea-9ce3-6ecd660c7117.png">

**Comment by thrust26** [comment]
> The 200% is an implementation detail that probably shouldn't have been exposed.

Maybe we should change that in the UI?

**Comment by thrust26** [comment]
I suppose we shouldn't change the wording.
