### ISSUE TITLE
Improvement to paddle autodetection

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#666]
The ROM at https://atariage.com/forums/topic/223257-arkanoid-2600/?do=findComment&comment=4562792 seems to not be autodetected as a paddle game.  Perhaps the detection can be improved for this case?

[paranoid_0.14b(NTSC).zip](https://github.com/stella-emu/stella/files/4775694/paranoid_0.14b.NTSC.zip)

**Comment by thrust26** [comment]
@sa666666 The problem is that its pattern "bit INPT0, bmi" is found in three joystick games too:
- Turbo (which would be fine, because it has paddle code inside, which is never evaluated)
- Spike's Peak (where it is data)
- Thrust (used for Booster Grip)

So we would break 3 auto detections for gaining 1. The code is existing in `ControllerDetector`, but commented out due to this.

**Comment by sa666666** [comment]
OK, I guess this is a case where the autodetection will just have to fail.  Feel free to close this.
