### ISSUE TITLE
can't mouse-click breakpoint on non-disassembled code areas

### ISSUE THREAD

**Issue by andrew-davie** [stella-emu/stella#668]
In the attached screenshot, I can add a breakpoint via "break ExitTitleScreen" but I can neither add nor remove that breakpoint via UI mouse-click on the breakpoint "dot" area. This has often proven frustrating to me, because I **know** the execution path will exit at that point, but because the disassembler hasn't disassembled it, I am prevented from putting a breakpoint there (via UI). I specifically want to do it via UI because I don't always have the label handy like in the example.

Although I suspect this was added as a safeguard (don't allow breakpoints in non-code areas), I think that was a mistake in thinking. I'd like to see that "safeguard" removed, and allow UI breakpoints at any point in the code view window.

<img width="1392" alt="Screen Shot 2020-06-21 at 9 05 53 pm" src="https://user-images.githubusercontent.com/16424075/85223080-66c04680-b403-11ea-908b-b18e32474b2b.png">

**Comment by sa666666** [comment]
I think the actual reason is that each line that represents a location in the address space stores that address, making it easy to have a BP there.  But a line that represents multiple bytes doesn't store any such address (since there is no single number that the line represents), and hence you can't create a breakpoint there.

Put another way, if you click on a line that contains 10 bytes to set a BP, which one should it apply to?  The current code doesn't know, so it disallows it completely.

**Comment by andrew-davie** [comment]
> Put another way, if you click on a line that contains 10 bytes to set a BP, which one should it apply to? The current code doesn't know, so it disallows it completely.

The clear and obvious answer to me, anyway, is "the first".

But failing that, how about allowing a breakpoint if the first byte's address is also the address of a label?  This would at least give the GUI the same functionality as the command-line.

**Comment by sa666666** [comment]
Seems, reasonable I guess.  Still doesn't solve the problem of being able to set a BP at the prompt that is not accessible graphically.  But then again, if you know how to use the prompt to set it, you know just as well how to unset it.
