### ISSUE TITLE
Toggling fullscreen mode doesn't work while a dialog is displayed

### ISSUE THREAD

**Issue by ale-79** [stella-emu/stella#670]
As title says, if the Time Machine dialog is on, ALT+ENTER displays the message "Fullscreen enabled" if in a window, or "Fullscreen Disabled" if in fullscreen, but it doesn't actually switch mode.

EDIT:
Actually it behaves the same with other dialogs as well

**Comment by thrust26** [comment]
Should be an easy fix. Thanks for posting.

**Comment by sa666666** [comment]
This is intentional.  Toggling fullscreen/windowed mode can change the resolution, and this can mess with currently displayed dialogs.  And since almost all dialogs can't be resized, this was a quick fix to deal with that.

However, the message about toggling fullscreen mode and it not actually happening is definitely a bug.  In that case, it shouldn't display any message at all, or perhaps display a message saying that a modeswitch can't happen when a dialog is active.

**Comment by thrust26** [comment]
For consistency, no message at all. There are multiple hotkeys which do not work in Time Machine mode.

**Comment by sa666666** [comment]
It's not just dialogs.  You also can't resize the window either when a dialog is active.  It's an issue with the underlying UI code/widgets, which was really never designed to be dynamically resizeable.
