### ISSUE TITLE
FEATURE REQUEST 7-Zip

### ISSUE THREAD

**Issue by Augusto7743** [stella-emu/stella#677]
Any chance to add 7-Zip in Stella ?
An complete ROM set zipped use less of 2 MB.
7-Zip in Stella is more to use an file format that is default to all emulators.
Thanks very much for read my post.
Have an nice day.

**Comment by sa666666** [comment]
Regular ZIP files are already well supported in Stella.  And since the file sizes are so small anyway, there's no need to add another compression scheme.  So we can't justify the amount of work required to have both ZIP and 7-Zip support, when for our purposes the former does everything that the latter one does.

Note that there is still work ongoing to make sure everything can be accessed from a ZIP file (currently, some items cannot be used if they're in an archive).  But ROMs can be in a ZIP file, and that has been supported for years.
