### ISSUE TITLE
Artifacts when aspect ratio correction is disabled

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#708]
There are random pixel missing or added when the zoom factor is a non-integer. The position and pattern are depending on the zoom factor and game. 

The bug happens in all renderers, except Software. could this be a driver problem?

Note: The bug is not related to the TIA objects. If you e.g. move Pitfall Harry over the ladder in the first example, the sprite shows the same pattern as the ladder (ball).

Examples:
Pitfall, 225%, few errors in playfield and players (trees, Harry, log, wall):
![Pitfall! (1982) (Activision)_2](https://user-images.githubusercontent.com/24360774/95551215-9e7ee880-0a0a-11eb-9061-28b2d0956858.png)

Pitfall, 250%, lots of errors, only playfield and ball in the lower half affected:
![Pitfall! (1982) (Activision)_1](https://user-images.githubusercontent.com/24360774/95550952-126cc100-0a0a-11eb-8f6a-5f36cfdad901.png)

Pitfall, 275%, very few errors in players (Harry, log):
![Pitfall! (1982) (Activision)_4](https://user-images.githubusercontent.com/24360774/95551323-db4adf80-0a0a-11eb-9ed5-1f4110abf85f.png)

Keystone Kapers, 225%, some errors in playfield and sprites (bottom radar, Kelly, escalator):
![Keystone Kapers (1983) (Activision)](https://user-images.githubusercontent.com/24360774/95552240-a8a1e680-0a0c-11eb-80d8-8487b6683650.png)

Keystone Kapers, 250%, lots of errors in playfield and sprites (bottom radar, floors, Kelly, escalator):
![Keystone Kapers (1983) (Activision)_1](https://user-images.githubusercontent.com/24360774/95552281-b7889900-0a0c-11eb-9eca-10863945101f.png)

Keystone Kapers, 275%, few errors in playfield and sprites (bottom radar, one floor, Kelly's hat, escalator, score):
![Keystone Kapers (1983) (Activision)_2](https://user-images.githubusercontent.com/24360774/95552543-24039800-0a0d-11eb-9b6a-5cb582b44963.png)

**Comment by ale-79** [comment]
I cannot reproduce the bug here (linux):
The only difference seems to be that with OpenGL, there's some smoothing when the zoom value is non-integer, even if I have "interpolation" turned off in the settings. 

OpenGl

200%
![Pitfall (1983) (CCE)_4](https://user-images.githubusercontent.com/24704739/95582292-ba01e780-0a3a-11eb-87f5-4f9cdcc79800.png)

225%
![Pitfall (1983) (CCE)](https://user-images.githubusercontent.com/24704739/95582316-c1c18c00-0a3a-11eb-98ff-3158e815735f.png)

250%
![Pitfall (1983) (CCE)_2](https://user-images.githubusercontent.com/24704739/95582330-c9813080-0a3a-11eb-82c6-75a24218f4ab.png)

Software
200%
![Pitfall (1983) (CCE)_5](https://user-images.githubusercontent.com/24704739/95582351-d3a32f00-0a3a-11eb-89b1-8f07810d66ba.png)

225%
![Pitfall (1983) (CCE)_1](https://user-images.githubusercontent.com/24704739/95582405-e87fc280-0a3a-11eb-8e50-80f7a0e15f65.png)

250%
![Pitfall (1983) (CCE)_3](https://user-images.githubusercontent.com/24704739/95582433-f03f6700-0a3a-11eb-8ad5-28a3d2a0168e.png)

All screenshots are taken in window mode, with Interpolation, Blargg and scanlines disabled.

**Comment by thrust26** [comment]
> I cannot reproduce the bug here (linux):
The only difference seems to be that with OpenGL, there's some smoothing when the zoom value is non-integer, even if I have "interpolation" turned off in the settings.

Neither can Stephen. We suppose this is a driver/OS issue. But we have to get rid of the smoothing too. Maybe we will only allow integer zooms when the aspect ratio correction is disabled.

**Comment by sa666666** [comment]
With the refactoring I'm working on, it is easy enough to reset the zoom to integer factor when aspect is disabled.  And then when re-enabling aspect correction, it will use whatever zoom factor that was previously being used.  TBH, this is probably best anyway, regardless of corruption, since aspect disabled implies you want pixel perfection, and that isn't guaranteed with non-integer zoom factors.

**Comment by sa666666** [comment]
In the end I think it's a driver issue.  But I would rather document that aspect disabled means you get integral zoom only.  "It's not a bug, it's a feature" 😈

**Comment by thrust26** [comment]
I suppose you are right.
