### ISSUE TITLE
Drag and drop dialogs

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#729]
Dialogs are currently put at fixed positions. Since they have their own surfaces, they could be dragged around using the mouse.

**Comment by sa666666** [comment]
Absolutely.  At least all but 'base' dialogs.  But do we _really_ want to go down that rabbit hole?  Then we could have window positions remembered for the next launch.  And windows that move in front of or behind each other.  At some point we're re-creating an entire windowing system here.  And that gets pretty far away from 2600 emulation :smiling_imp:

**Comment by thrust26** [comment]
I will experiment with it in an extra branch. If it becomes too complicated, I will abort.

But currently it looks quite straightforward.

Why "but 'base' dialogs"?

**Comment by sa666666** [comment]
In windowed mode at least, base dialogs are the underlying ones (launcher and debugger).  You can't move them, since there is no surrounding space to 'move' them into; they already take up the entire area.  Also, they don't have titlebars, which also signifies that they aren't dialogs in the normal sense.  In some sense, they are the container/screen for the other dialogs (ie, that's why they inherit from `DialogContainer` :smile: )  It makes sense to move dialogs within that, but not that bottom-most one.

**Comment by thrust26** [comment]
Got you.

**Comment by thrust26** [comment]
Makes little sense if you cannot move dialogs outside the main window.

**Comment by sa666666** [comment]
Yep, if you want dialogs in separate windows, being able to move anywhere onscreen independently, then that means creating _multiple windows_.  SDL2 allows that, but it would be a **major redesign** of Stella, which has existed as a single window since its creation.
