### ISSUE TITLE
Mac Touch Bar enhancement

### ISSUE THREAD

**Issue by jc13git** [stella-emu/stella#744]
I didn't see this searching through the issues list, but is it feasible to have the select/reset, etc. controls natively on the Touch Bar (for equipped Macs)?  I've tried using the add-on touch bar tools, but can't get Stella to recognize the "button" presses.

**Comment by thrust26** [comment]
Does SDL2 support the touch bar?

**Comment by DirtyHairy** [comment]
Nah, you'll have to do that using "native" MacOS code. It's feasible, and I have been thinking about adding it, but you'll have to drill a hole from the platform specific code to the event subsystem, and I think that's a lot of work for little gain.

**Comment by sa666666** [comment]
One possibility is to have the code generate an `SDL_Event` and push it into the event queue, so at least the rest of the code won't even recognize that it's a platform-specific event.  But that still requires the Mac-specific classes to talk to the SDL-specific eventhandler class, like @DirtyHairy says.  Perhaps it can be generalized so that platforms can 'register' events that they want to know about and respond to.

But personally I can't do anything with this, since I don't have a Mac with that type of keyboard.

**Comment by thrust26** [comment]
And what would the bar be useful for?

**Comment by DirtyHairy** [comment]
My vision would have been something like an image of a cartridge slot in the middle, and difficulty switches and reset / start buttons to the left and right of it, somewhat like a real Atari.

I think that would look nice and somewhat help games that actively use those, but overall, I think the benefit is rather marginal.

**Comment by jc13git** [comment]
Just as info, a screenshot of the Atari800MacX Touch Bar is attached.  Just makes it convenient so you don't have to remember the function key assignments.
<img width="1085" alt="Touch Bar Shot 2020-12-10 at 8 42 55 PM" src="https://user-images.githubusercontent.com/43517966/101850871-96d1e200-3b28-11eb-9c9c-6c1bc93cfe2b.png">

**Comment by sa666666** [comment]
Since newer Macs seem to be discontinuing this hardware, and none of the development team have it, I don't think it's feasible to add this.

**Comment by thrust26** [comment]
I was about to suggest the same.
