### ISSUE TITLE
Stella not displaying special characters in directories

### ISSUE THREAD

**Issue by anonymous7002** [stella-emu/stella#752]
e.g. Käynnistä-valikko (Start Menu) gets displayed as K ynnist -valikko.

**Comment by sa666666** [comment]
Already reported in https://github.com/stella-emu/stella/issues/751.

**Comment by thrust26** [comment]
Actually this is different. This one is about certain language specific chars displayed as blanks. 

But fixing this would require a **major** change in font handling for a relatively small improvement. So IMO we should not fix it.

**Comment by sa666666** [comment]
This is actually how #751 works for me (in Linux), which is why I marked it as duplicate.

Agreed about the underlying issue.  Stella is basically English and ASCII-only, and I really don't want to get into Unicode handling, which is what we would need here.  The entire UI would have to be revamped, entirely new fonts created, a new rendering system, etc.  Basically, it would be less work to move to a completely different toolkit.  We _may_ be able to deal with umlauts if they fall in the upper ASCII range, but anything Unicode is out of the question here.

**Comment by thrust26** [comment]
Interesting. Under Windows some chars are displayed as blanks and some (e.g. that special 'z' from #751) are displayed as their base chars.
