### ISSUE TITLE
PAL color loss in PAL60 not supported

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#76]
PAL color loss seems to be linked to the number of scan lines (it works in NTSC50 too!), but it should be linked to the TV mode instead.

**Comment by sa666666** [comment]
Well, since we haven't re-implemented it yet, now is the time to consider these changes.  I have some questions about this too when the time comes, since I don't use a PAL system and only vaguely understand what the output should look like.  The old core simply changes to black and white.

For clarification, of the 6 modes supported by Stella, which ones should PAL colour loss apply to:
NTSC, PAL, SECAM, NTSC50, PAL60, SECAM60??

**Comment by thrust26** [comment]
The colors lose all saturation, the brightness should stay the same. So to be 100% precise, for each color value there would have to be a matching grey value. But I don't think that's required, since developers will avoid this happening. Its more a debugging feature.

I don't think SECAM is affected, only PAL. Therefore Only PAL(50) and PAL60 should react to an odd scan line count.

**Comment by DirtyHairy** [comment]
I have not yet looked at how this was done in the old core, but my vague idea for implementing this was raising a flag on the TIA after an odd frame and using this to select an adapted palette when drawing the buffer.

**Comment by sa666666** [comment]
This is essentially what is in the old core.  The only issue is that while there are 128 colours in the TIA palette, Stella stores them in a 256-colour array.  The even indices apply to normal mode, and the odd indices to PAL colour loss (which is pre-calculated).  This leads to another problem, in that the Blargg effects only work on 128 colours, and hence Blargg and PAL colour-loss don't work at the same time (essentially, PCL is disabled in Blargg mode).

**Comment by DirtyHairy** [comment]
Does Blargg run on individual frames, or does it combine information from several frames?

**Comment by sa666666** [comment]
There are basically 4 rendering modes and 2 framebuffers (current and previous).

kNormal:  Normal render, no blargg, uses current buffer only

kPhosphor:  Normal phosphor, no blargg, uses current and previous buffers

kBlarggNormal:  blargg effects, uses current buffer

kBlarggPhosphor:  blargg effects, uses current and previous buffers

The last two consist of two methods, which take in either one or both buffers (as applicable).  For the last case, the blending of the two buffers is done by Blargg itself (so it gets two frames and blends them, instead of getting the output of kPhosphor (two frames blended) as input and rendering a single frame.

In any event, the whole thing should be simplified.  We have normal, phosphor and blargg, when really there should be only one (blargg, which emulates what a real TV would show).

**Comment by thrust26** [comment]
If Blargg supports phosphor, why should we add our own method too? (see #75)

**Comment by sa666666** [comment]
This is now fixed in https://github.com/stella-emu/stella/commit/fb5daa483b4d04cd8ce15a78e485831f217a02b4.

**Comment by thrust26** [comment]
reopened by mistake
