### ISSUE TITLE
3E+ enters debugger with "Random Startup Bank"

### ISSUE THREAD

**Issue by mohhingman** [stella-emu/stella#800]
When a 3E+ ROM is loaded, and Developer mode is enabled, Stella will always halt execution and enter debugger when "Random Startup Bank" is ticked. This occurs even on the 3E+ roms that are bundled in the Stella test folders. The scheme is intolerant of a random startup bank; therefore should it allow this option? Or is this an expected behaviour?

**Comment by thrust26** [comment]
Sounds like a bug, I will check.

**Comment by andrew-davie** [comment]
"The last 1K ROM ($FC00-$FFFF) segment in the 6502 address space (ie: $1C00-$1FFF)
  is initialised to point to the FIRST 1K of the ROM image, so the reset vectors
  must be placed at the end of the first 1K in the ROM image."

Since the reset vectors are expected to be switched in, by necessity 3E+ requires that first 1K to be switched in.
