### ISSUE TITLE
FSNode exception when in invalid directory

### ISSUE THREAD

**Issue by thrust26** [stella-emu/stella#888]
If a browser dialog starts in a non-existing directory and the user tries to navigate away from is, `FilesystemNode::getName()` throws an invalid access exception.

Happened to me in the debugger when trying `savedis ?`. The directory was set to `c:\users\tjentzsch\desktop` which does not exist anymore on my computer (because OneDrive redirected it).

**Comment by sa666666** [comment]
I'll look into it.

**Comment by sa666666** [comment]
@thrust26, I'm having trouble re-creating this issue.  The problem is, upon startup we test for directories to exist and be usable.  And if not, the directory is created.  Did this happen while Stella was running?  Because that test only happens at startup.  So I guess the only way this can happen is if the directory existed on startup, and was then deleted while Stella was running.

**Comment by thrust26** [comment]
No, the directory did not exist at startup. I was unable to create the 'Desktop' directory manually. So I suppose that's what happened to Stella too, when it tried to create the directory.

**Comment by sa666666** [comment]
OK, I can test for that.  Just make it so the makedir fails, and see what happens.

**Comment by sa666666** [comment]
Yep, when I get to my Windows machine.  Using Linux here at work right now.

**Comment by sa666666** [comment]
@thrust26, please try this code and see if it fixes your original issue.  It fixes it on my end.
