### ISSUE TITLE
UI Suggestion -> Different layout for new Launcher

### ISSUE THREAD

**Issue by splendidnut** [stella-emu/stella#906]
This a suggestion for a tweak to the layout of the controls at the top of the launcher.  You all may have already had a lot of discussions regarding the layout... but I figured I would throw this idea out there, just in case.

New layout (mock-up):
![image](https://user-images.githubusercontent.com/61911172/175785484-2da246dd-d564-46c3-9cbd-3efa2db255cc.png)

This changes things to be in the order of Navigation, Filtering, Selection.  Which from a UX perspective is a more natural layout of the control hierarchy.  Also I pushed the Options button to be over by the help button, being as that seems to make more sense instead of being next to filtering box.... and I didn't want to push over the directory breadcrumbs more than necessary.

I'm still in the process of re-doing my CMake files to work with the latest codebase (last time I did that was for version 6.2.1), so it'll be a bit before I can try and implement this in a code branch.

**Comment by thrust26** [comment]
> You all may have already had a lot of discussions regarding the layout.

Actually not. I am doing the UI changes on my own. 😄 

And I can follow your thoughts, your order of navigation first and filter second makes sense. Not sure about the Options and where the Reload button should go. I think the options should be positioned very prominent, but maybe that's because I am a developer and use it more frequently than other people. 

Anyway, I have plenty of time to think about it now. And wait for your results.
