### ISSUE TITLE
Frame reset when using certain breakpoints

### ISSUE THREAD

**Issue by nsn** [stella-emu/stella#92]
Stella Version: 4.7.3 (OSX)

I encounter a strange "frame reset" issue when using certain breakpoints in the debugger.
If I `stella -debug` my project and set the breakpoint to after the VSYNC-wait I encounter seemingly random "frame resets": the scanline counter resets to 0 (even though the frame counter stays the same)

I put together a minimalist test case in this [gist](https://gist.github.com/nsn/ef763585571376fa07d7bad82470c116)

If I set the breakpoint to Section0 ($F047) and step through the `sta wsync` the scanline counter resets, If I set the breakpoint to DrawScreen ($F03C) and step (Scan +1) through the VSYNC wait manually everything works perfectly.

I can influence the line this issue occurs on by adjusting the value I write to TIM64T (#VBLANK_WAIT), but not reliably.

Is this expected behaviour? Am I doing anything wrong?

**Comment by sa666666** [comment]
This part of the code is currently being worked on for Stella 5.0, so I can't comment on 4.7.3 behaviour until we finish the applicable code in 5.0 and see if the issue still occurs.

**Comment by nsn** [comment]
allright, thanks for looking into it, I'll test it with the 5.0 release

**Comment by sa666666** [comment]
This now seems to be fixed in the latest code.  I've looked at both test cases, and they both correctly step from scanline 36 to scanline 37, and when rewinded go back to line 36 again.  In Stella 4.7.3, in the first case the scanline was being reset to 0, and doing a rewind never did set it back to 36.

Thanks for the bug report,
Steve A.
