### ISSUE TITLE
Instruction lda INPT0 doesn't have D7=1 in paddle mode

### ISSUE THREAD

**Issue by sa666666** [stella-emu/stella#96]
Further explanation in the AtariAge thread http://atariage.com/forums/topic/259633-testing-the-new-stella-tia-core/page-5#entry3703571.  Works in previous version of Stella and on real hardware.

**Comment by sa666666** [comment]
Seems like it might be related to https://github.com/stella-emu/stella/commit/146d0afe4fbf2dff007567ead70e090c6dce8bf6, but I'm not sure.  @DirtyHairy, what do you think?

**Comment by DirtyHairy** [comment]
@sa666666 , I thought so as well, but after looking closer at the issue, I think not. The heart of the problem seems to be that the first read of the paddle controller always returns the maximum of 0x7FFFFFFF --- the value that signifies "no paddle at all". This can also be reproduced  in 4.7.3 if you run Stella with `debug`, set a breakpoint in the `LDA INPT0` and hit run: the read will return 0x08.

I think what is happening that this is a race between mouse I/O and the read: if the read happens before the first mouse events are digested, then the resistance read will be 0x7FFFFFFF, and the simulated cap will not charge. The relevant difference between 4.7.3 and 5 may be the difference in how frames are counted --- I think the main loop spins more often before the relevant read in the old core.

Commit 38b452e fixes this by setting the resistance to 0 instead of 0x7FFFFFFF in the paddle constructor. What do you think?

**Comment by sa666666** [comment]
Seems fine to me.  The initial resistance could have always been at 0 instead of the max upper range; I guess it was a 50/50 chance that it worked for so long.
