### ISSUE TITLE
Delay on RSYNC + 220 max colorclock?

### ISSUE THREAD

**Issue by Thomas-de-Bock** [stella-emu/stella#967]
Sorry in advance if this isn't the place to ask, but I noticed that after writing to RSYNC, the colorclock isn't immediately reset, only the instructions afterwards. I also noticed that the color clock resets after reaching 220, but to my understanding it should have a max value of 228 no? Also curious as to why the INTIM value can't be modified in the debugger like other values. Anyways thanks in advance and big thanks for the stella emulator + debugger, it's been extremely helpful developing my own emulator.

**Comment by thrust26** [comment]
I can only answer the last question: INTIM is a register which can only be read. The other ones are for @DirtyHairy.

**Comment by DirtyHairy** [comment]
Howdy! Where do you get the notion that the color clock only counts to 220? It definitely counts to 228 😏 However, Stella steps instruction by instruction, so if you step an instruction with three cycles (= nine color clocks) starting at 220, it'll wrap in this step.

As for rsync, the color clock counter is set to 225 in the cycle in which the write is executed, so it will wrap to zero the next cycle. The behaviour was originally determined with test programs, the only way to find a deeper explanation is to go into the schematics.

**Comment by Thomasdb05** [comment]
Oooh I'm blind it said unwind 4 cycles but I forgot to convert it to the color clock my apologies. Also I see, I thought when it said "This address resets the horizontal sync counter to define the beginning of horizontal blank time" It was referring to the previous HBLANK, your explanation makes sense. And I understand INTIM is read only, I just thought since its assigned a random value at start there would be some way of changing that starting value, but I guess that could maybe be done with savestates? Anyways thanks so much for responding that clears some things up!

**Comment by Thomasdb05** [comment]
Wait, sorry to bother again, but if RSYNC sets the colorclock to 225 on the same cycle as the write occured, how can this happen? (Pitfall):
![image](https://user-images.githubusercontent.com/78592830/235124189-5c515156-e348-4a9a-9d73-5e2feff4a356.png)
![image](https://user-images.githubusercontent.com/78592830/235124298-98aebeef-b42b-49ac-8573-a98407c24fc8.png)
![image](https://user-images.githubusercontent.com/78592830/235124363-b855a0e7-b808-4d9e-af7d-fe5922d5cd9f.png)

Only after TXS does it wrap around, after the write to RSYNC nothing out of the ordinary happens to the color clock.

**Comment by thrust26** [comment]
https://github.com/stella-emu/stella/issues/5 😄
