### ISSUE TITLE
delayed position writes, not present in queue?

### ISSUE THREAD

**Issue by Thomas-de-Bock** [stella-emu/stella#970]
Although this is definitely the correct behavior as without it the positions are way off, should this not be in the queued writes, and what is causing this odd behavior? I understand HMOVE can be a mess depending on the timing of calling the strobe, but how come it: After decrementing from 6, wrapping around to 160, then going down to 154 then up to 156, it then jumps to 0, all without any additional writes to HMOVE, HMCLR, or any HMxx addresses.
![image](https://github.com/stella-emu/stella/assets/78592830/66ee8c87-1557-42d0-9077-300c8549c5dd)
![image](https://github.com/stella-emu/stella/assets/78592830/aa8304fe-95ac-4b6f-8dde-d5a3ecf3ae2a)
![image](https://github.com/stella-emu/stella/assets/78592830/ade4067d-46cf-4cf1-b26a-e67117e952fb)
![image](https://github.com/stella-emu/stella/assets/78592830/2c1075d7-c20f-4daf-b7c5-53b360685e9d)
![image](https://github.com/stella-emu/stella/assets/78592830/c1cdab49-9da3-44bd-b60a-6fb39396de76)
Not sure under what category these writes fall, but I think some debugger section regarding them could be helpful, but then again I truly don't understand what is causing this.

**Comment by Thomas-de-Bock** [comment]
Seaquest (1983) (Activision)

**Comment by ale-79** [comment]
> Not sure under what category these writes fall, but I think some debugger section regarding them could be helpful...

There aren't "writes" to be shown. It's just that HMOVE effects aren't immediate, and it takes a certain amount of cycles to complete its operations.
Each object has a "position counter" that is clocked only during the visible part of a scanline. When the counter wraps around the object is displayed. Normally  the counter wraps around always on the same position (corresponding to the last" RESxx" strobe).


There are 2 effects of an HMOVE strobe: 
1 - extra clocks to the position counters of each objects during the horizontal blanking period (the number of these extra clocks depends on the value stored in the corresponding "HMxx" register). Each one of these extra clocks will cause the counter to wrap around one pixel earlier, that is to shift the object **to the left**. 
2 - an extended horizontal blank area (HMOVE bar), during which the counters do NOT receive the "regular" clocks. This results in the position counter of every object to wraparound 8 pixels later, that is to be shifted 8 pixels **to the right**.

(Check Andrew Towers' "TIA Hardware Notes" for a better explanation of what's going on)

The "Pos#" field in the debugger is the "expected" position where the object would be drawn if the corresponding counter would only receive the regular clocks. So you see it changing while HMOVE operations take place.


Considering Player 1 in the "Seaquest" example above, on scanline 67 HMOVE is strobed at cycle 3, and "HMP1" value is 6. This corresponds to **14** extra clock pulses.
The pulses will take place every 4 TIA cycles (1.33 CPU cycles), with the first one occurring at cycle 5.33. 
In the debugger the minimum step you can advance is one instruction.

So, keep stepping through the code:
- "`lda #$74`" ends at cycle 5. No extra clocks yet, so no change in the expected position (**6**).

- "`eor ram_85`" ends at cycle 8. Pos# is now **4**, because of the two extra clocks (at cycle 5.33 and 6.67) each one causing the object to be displayed 1 pixel earlier (to the left).

- "`and ram_86`" ends at cycle 11. 3 extra clocks (at cycle 8, 9.33 and 10.67) -> Pos# is now **1**.

- "`sta COLUP0`" ends at cycle 14. 2 extra clocks (at cycle 12 and 13.33) -> Pos# wraps around and is now **159**.

- "`ldx ram_E0`" ends at cycle 17. 2 extra clocks (at cycle 14.67 and 16) -> Pos# is now **157**.

- "`lda Lfcfb,x`" ends at cycle 21. 3 extra clocks (at cycle 17.33, 18.67 and 20) -> Pos# is now **154**

- "`sta ram_98`" ends at cycle 24. the last 2 extra clocks occur (at cycle 21.33 and 22.67). This would decrement #Pos by 2. But the position of the electron beam is now 4 pixel into the HMOVE bar. So we subtract 2 because of the extra HMOVE clocks, and add 4 because of the missed "regular" clocks in in the portion of the HMOVE bar that the beam has passed -> Pos# is now **156**

- "`lda #$fd`" ends at cycle 26. No more extra clocks, but 4 more pixels of HMOVE bar -> Pos# wraps around again and is now **0**.

**Comment by Thomas-de-Bock** [comment]
Thank you so much for the very well explained response. I had no idea this was how the position counters worked, that explains why they're not in memory and a lot of the odd behavior surrounding HMOVE. That link to Andrew Towers' hardware notes also cleared a lot of misunderstandings I had up. Thanks a lot, I really appreciate it!
